import { describe, expect, it, vi } from 'vitest'
import pokedexJson from '../../data/reference/pokedex.json'
import { resolveBreedingBabyTemplateStageV1 } from '../../shared/breeding/babyTemplate'
import {
  createBreedingBabyTemplateAuthorityV1,
  createBreedingMarsupialProviderTraitV1,
  parseAuthoritativeBreedingBabyTemplateAuthorityV1,
  resolveBreedingMarsupialBabyTemplateV1,
} from '../../server/domain/breeding/babyTemplate'
import type { CharacterSheet } from '../../src/types/characterSheet'
import { pokemonHasActiveBabyTemplate, pokemonHasActiveMarsupialBabyTemplate, pokemonMarsupialBabyActionRestricted, resolveCapabilities, resolvePokemonBabyTemplateStage, resolveSkills, resolveStats } from '../../src/utils/sheets/pokemonDerived'
import { reconcileServerOwnedBreedingBabyTemplate } from '../../src/utils/sheets/pokemonBabyTemplate'

const EGG_ID='pokemon-egg:v1:88888888888888888888888888888888' as const
const OPTION_ID='option:v1:88888888888888888888888888888888' as const
const effects=(penalty:2|3|4=4)=>({baseStatPenaltyEach:penalty,skillRankPenalty:1 as const,capabilityPenalty:2 as const,sizePercentOfAdult:65,recoveryBaseStatPointsEachInterval:1 as const,recoveryIntervalLevels:5 as const,recoveryStepCount:penalty,removeSkillAndCapabilityPenaltyAfterFinalRecovery:true as const})
const authority=()=>createBreedingBabyTemplateAuthorityV1({sourceEggId:EGG_ID,babyTemplate:{applied:true,choiceOptionId:OPTION_ID,choiceEvidenceId:'breeding.baby-template.gm-authority',effects:effects()},marsupial:null})
const sheet=(level=1):CharacterSheet=>{const frozen=authority();return{slug:'baby-bulbasaur',nickname:'Baby',species:'Bulbasaur',level,totalExp:0,nature:'Cuddly',babyTemplate:true,babyTemplateMechanics:{schemaVersion:1,applicationKind:frozen.applicationKind,effects:frozen.effects},serverPrivate:{breedingBabyTemplate:frozen},stats:{},skills:{},capabilities:{}}}

describe('BR-067 authoritative Baby Template lifecycle',()=>{
  it('recovers one Base Stat point every five Levels and removes all remaining penalties after the final step',()=>{const stages=[1,5,10,15,20].map(level=>resolvePokemonBabyTemplateStage(sheet(level)));expect(stages.map(stage=>stage?.remainingBaseStatPenaltyEach)).toEqual([4,3,2,1,0]);expect(stages.map(stage=>stage?.sizePercentOfAdult)).toEqual([65,73,82,91,100]);expect(stages[0]).toMatchObject({active:true,skillRankPenalty:1,capabilityPenalty:2,nextRecoveryLevel:5,finalRecoveryLevel:20});expect(stages[4]).toMatchObject({active:false,skillRankPenalty:0,capabilityPenalty:0,nextRecoveryLevel:null});expect(pokemonHasActiveBabyTemplate(sheet(19))).toBe(true);expect(pokemonHasActiveBabyTemplate(sheet(20))).toBe(false)})
  it('applies typed stat, Skill, movement, size, and growth effects without changing Species JSON',()=>{const speciesBefore=JSON.stringify(pokedexJson);const adult:CharacterSheet={...sheet(20),babyTemplate:false,babyTemplateMechanics:undefined,serverPrivate:undefined};const baby=sheet(1);const adultStats=resolveStats(adult),babyStats=resolveStats(baby);for(const stat of babyStats)expect(stat.base).toBe(Math.max(1,adultStats.find(value=>value.key===stat.key)!.base-4));const adultAthletics=resolveSkills(adult).find(value=>value.key==='athletics')!.value;const babyAthletics=resolveSkills(baby).find(value=>value.key==='athletics')!.value;expect(adultAthletics).toMatch(/^\d+d6/u);expect(Number.parseInt(babyAthletics,10)).toBe(Math.max(1,Number.parseInt(adultAthletics,10)-1));const babyCaps=resolveCapabilities(baby);expect(babyCaps.rows.find(row=>row.label==='Overland')?.value).toBe(3);expect(String(babyCaps.rows.find(row=>row.label==='Size')?.value)).toContain('65% adult');expect(resolveStats(sheet(20))).toEqual(adultStats);expect(JSON.stringify(pokedexJson)).toBe(speciesBefore)})
  it('preserves private authority against an editable false flag or forged public mechanics and materializes recovery from Level',()=>{const current=sheet(19);const requested={...current,level:20,babyTemplate:true,babyTemplateMechanics:{schemaVersion:1 as const,applicationKind:'campaign-option' as const,effects:effects(2)}};const reconciled=reconcileServerOwnedBreedingBabyTemplate(current,requested);expect(reconciled.babyTemplate).toBe(false);expect(reconciled.babyTemplateMechanics).toEqual(current.babyTemplateMechanics);const stillActive=reconcileServerOwnedBreedingBabyTemplate(sheet(10),{...sheet(10),babyTemplate:false});expect(stillActive.babyTemplate).toBe(true);expect(()=>reconcileServerOwnedBreedingBabyTemplate(sheet(20),{...sheet(20),level:19,babyTemplate:true})).toThrow('cannot be reversed')})
  it('forces Marsupial minus five through Level 24 and ends it exactly at Level 25',()=>{const baby=resolveBreedingMarsupialBabyTemplateV1();const frozen=createBreedingBabyTemplateAuthorityV1({sourceEggId:EGG_ID,babyTemplate:baby,marsupial:createBreedingMarsupialProviderTraitV1()});const mechanics={schemaVersion:1,applicationKind:frozen.applicationKind,effects:frozen.effects};const marsupialSheet={...sheet(24),slug:'baby-kangaskhan',species:'Kangaskhan',babyTemplateMechanics:mechanics,serverPrivate:{breedingBabyTemplate:frozen}};expect(resolveBreedingBabyTemplateStageV1({mechanics,currentLevel:24})).toMatchObject({active:true,remainingBaseStatPenaltyEach:1,nextRecoveryLevel:25});expect(resolveBreedingBabyTemplateStageV1({mechanics,currentLevel:25})).toMatchObject({active:false,remainingBaseStatPenaltyEach:0,finalRecoveryLevel:25});expect(pokemonHasActiveMarsupialBabyTemplate(sheet(1))).toBe(false);expect(pokemonHasActiveMarsupialBabyTemplate(marsupialSheet)).toBe(true);expect(pokemonMarsupialBabyActionRestricted(sheet(1),[])).toBe(false);expect(pokemonMarsupialBabyActionRestricted(marsupialSheet,[])).toBe(true);expect(pokemonMarsupialBabyActionRestricted(marsupialSheet,['Parental Bond'])).toBe(false)})
  it('rejects malformed, enriched, and hash-tampered authority instead of treating editable state as provenance',()=>{const frozen=authority();expect(()=>parseAuthoritativeBreedingBabyTemplateAuthorityV1({...frozen,definitionSha256:'0'.repeat(64)})).toThrowError(expect.objectContaining({code:'breeding.baby-template.hash-mismatch'}));expect(()=>resolveBreedingBabyTemplateStageV1({mechanics:{schemaVersion:1,applicationKind:'campaign-option',effects:{...effects(),extra:true}},currentLevel:1})).toThrowError(expect.objectContaining({code:'breeding.baby-template.unknown-field'}));const forged=reconcileServerOwnedBreedingBabyTemplate({slug:'adult',nickname:'Adult',species:'Bulbasaur',level:30,totalExp:0},{slug:'adult',nickname:'Adult',species:'Bulbasaur',level:1,totalExp:0,babyTemplate:true,babyTemplateMechanics:{schemaVersion:1,applicationKind:'campaign-option',effects:effects()},serverPrivate:{breedingBabyTemplate:frozen}});expect(forged.babyTemplate).toBe(false);expect(forged).not.toHaveProperty('babyTemplateMechanics');expect(forged).not.toHaveProperty('serverPrivate');const getter=vi.fn(()=>frozen.definitionSha256);const enrichedHashes=[] as string[];Object.defineProperty(enrichedHashes,'0',{enumerable:true,get:getter});Object.defineProperty(enrichedHashes,'length',{value:1,writable:true});expect(()=>parseAuthoritativeBreedingBabyTemplateAuthorityV1({...frozen,providerEvidenceDefinitionSha256s:enrichedHashes})).toThrow();expect(getter).not.toHaveBeenCalled();expect(resolvePokemonBabyTemplateStage({slug:'editable',nickname:'Editable',species:'Bulbasaur',level:1,totalExp:0,babyTemplate:false})).toBeNull()})
})
