import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(testDir, '../..')

const readSource = (relativePath: string): string => readFileSync(resolve(repoRoot, relativePath), 'utf8')

describe('map page route authority', () => {
  it('wires clicked live-play movement through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const livePlayTrackedTokenPredictions = ref<Readonly<Record<string, TrackedLivePlayTokenPrediction>>>({})')
    expect(mapPage).toContain('const livePlayTokenCorrectionNoticeController = createLivePlayTokenCorrectionNoticeController()')
    expect(mapPage).toContain('const livePlayTokenCorrectionNotice = livePlayTokenCorrectionNoticeController.notice')
    expect(mapPage).toContain('onCommandAccepted: handleLivePlayCommandAccepted')
    expect(mapPage).toContain('onCommandRejected: handleLivePlayCommandRejected')
    expect(mapPage).toContain('return `Move corrected by the server; ${prediction.tokenLabel} returned to its last confirmed position.`')
    expect(mapPage).toContain('return `Conditions corrected by the server; ${prediction.tokenLabel} returned to its last confirmed conditions.`')
    expect(mapPage).toContain('livePlayTokenCorrectionNoticeController.show({')
    expect(mapPage).toContain("transition.reason !== 'stale-revision'\n    && livePlayTokenCorrectionNoticeController.hasCorrectedOpId(transition.response.opId)")
    expect(mapPage).toContain('if (acceptedPlacementId) livePlayTokenCorrectionNoticeController.clearForPlacement(acceptedPlacementId)')
    expect(mapPage).toContain('livePlayStateMachine.clearCommandError()')
    expect(mapPage).toContain('return playerProfileTokenControlModel.value.notice')
    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeMove = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const predictedMove = newPendingMovePredictionForPlacement(pendingPredictionOpIdsBeforeMove, payload.id)')
    expect(mapPage).toContain('if (predictedMove) {\n    rememberLivePlayPredictedToken(predictedMove, livePlayTokenLabel(payload.id))\n    clearSelection()\n  }')
    expect(mapPage).toContain('const moveWasPredicted = predictedMove !== null\n    if (!moveWasPredicted) clearSelection()')
    expect(mapPage).toContain('if (!result.dispatched) {\n      if (result.opId) forgetLivePlayPredictedToken(result.opId)\n      return\n    }')
    expect(mapPage).toContain('await Promise.resolve(attackOfOpportunityPanel?.provokeMovementAttackOfOpportunity({')
  })

  it('wires clicked live-play facing through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeTurn = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const dispatch = livePlayCommands.turnToken({ placementId: id, facing })')
    expect(mapPage).toContain('const predictedTurn = newPendingTurnPredictionForPlacement(pendingPredictionOpIdsBeforeTurn, id)')
    expect(mapPage).toContain('rememberLivePlayPredictedToken(predictedTurn, livePlayTokenLabel(id))')
    expect(mapPage).toContain('if (result.opId) forgetLivePlayPredictedToken(result.opId)')
    expect(mapPage).toContain('const turnWasPredicted = predictedTurn !== null\n    if (!turnWasPredicted) clearSelection()')
    expect(mapPage).toContain('LIVE_PLAY_COMMAND_TYPES.TURN_TOKEN,')
    expect(mapPage).toContain('turnPlacementForSetupEdit(id)\n    clearSelection()\n    return')
  })

  it('wires token-level live-play prediction affordances into the map renderer', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')
    const tokenRenderer = readSource('src/utils/isometric/tokenRenderer.ts')

    expect(mapPage).toContain('const livePlayPendingPredictionTokenIds = computed(() => Array.from(new Set(')
    expect(mapPage).toContain('const livePlayGlobalTransportPending = computed(() => (')
    expect(mapPage).toContain(':live-play-pending-token-ids="livePlayPendingPredictionTokenIds"')
    expect(mapPage).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId"')
    expect(mapPage).toContain(':live-play-correction-token-ids="livePlayCorrectionTokenIds"')
    expect(mapPage).toContain(':live-play-token-correction-notice="livePlayTokenCorrectionNotice"')
    expect(scenePanel).toContain('class="live-play-token-correction-notice"')
    expect(scenePanel).toContain(':live-play-pending-token-ids="livePlayPendingTokenIds ?? []"')
    expect(scenePanel).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId ?? {}"')
    expect(sceneRenderer).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId ?? {}"')
    expect(sceneRenderer).toContain(':live-play-correction-token-ids="livePlayCorrectionTokenIds ?? []"')
    expect(isometricGrid).toContain('const livePlayPendingTokenIdSet = computed(() => new Set(props.livePlayPendingTokenIds ?? []))')
    expect(isometricGrid).toContain('const renderedPokemons = computed<SpawnedPokemon[]>(() => props.pokemons.map((pokemon) => {')
    expect(isometricGrid).toContain('const pendingConditions = props.livePlayPendingConditionsByTokenId?.[pokemon.id]')
    expect(isometricGrid).toContain('pending: livePlayPendingTokenIdSet.value.has(pokemon.id)')
    expect(isometricGrid).toContain('corrected: livePlayCorrectionTokenIdSet.value.has(pokemon.id)')
    expect(tokenRenderer).toContain('options: { hovered?: boolean; pending?: boolean; corrected?: boolean } = {}')
    expect(tokenRenderer).toContain('corrections temporarily reserve the red invalid ramp for rollback feedback')
  })

  it('wires local token selection and hover into ephemeral presence without changing control authority', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')

    expect(mapPage).toContain('const hoveredPresenceTokenId = ref<string | null>(null)')
    expect(mapPage).toContain('const visiblePresenceTokenIds = computed<readonly string[]>(() => spawnedPokemon.value.map((pokemon) => pokemon.id))')
    expect(mapPage).toContain('visibleTokenIds: visiblePresenceTokenIds')
    expect(mapPage).toContain('presenceTokenIdIfVisible(selectedId.value)')
    expect(mapPage).toContain('presenceTokenIdIfVisible(hoveredPresenceTokenId.value)')
    expect(mapPage).toContain('@hover-pokemon="setHoveredPresenceToken"')
    expect(mapPage).toContain('if (isPlayer.value) clearSelection()')
    expect(scenePanel).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(scenePanel).toContain('@hover-pokemon="emit(\'hover-pokemon\', $event)"')
    expect(sceneRenderer).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(sceneRenderer).toContain('@hover-pokemon="emit(\'hover-pokemon\', $event)"')
    expect(isometricGrid).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(isometricGrid).toContain("emit('hover-pokemon', nextId)")
    expect(mapPage).toContain('selectPlacement(id)')
    expect(mapPage).not.toContain('remoteTokenLock')
  })

  it('wires the live-play latency debug panel behind an explicit query flag', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const panel = readSource('src/components/map/LivePlayLatencyDebugPanel.vue')

    expect(mapPage).toContain("import LivePlayLatencyDebugPanel from '~/components/map/LivePlayLatencyDebugPanel.vue'")
    expect(mapPage).toContain("const livePlayLatencyDebugEnabled = computed(() => route.query.debugLivePlayLatency === '1')")
    expect(mapPage).toContain('<LivePlayLatencyDebugPanel\n        v-if="livePlayLatencyDebugEnabled"\n        :traces="livePlayCommands.commandTraces.value"\n      />')
    expect(panel).toContain('Pred → SSE')
    expect(panel).toContain('Pred → HTTP')
    expect(panel).toContain('HTTP → adopt')
    expect(panel).toContain('SSE → adopt')
    expect(panel).toContain("trace.resourceSummary ?? 'resource scope unavailable'")
    expect(panel).toContain("opId.slice(-8)")
    expect(panel).not.toContain('profileId')
    expect(panel).not.toContain('payload.')
  })

  it('uses the saved map route regardless of the session query parameter', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('key: (route) => `map-${routeSlugParam(route.params)}`')
    expect(mapPage).toContain('useLiveSheets({\n  autoHydrate: false,\n  hydrationOwner: `map:${slug}`,\n})')
    expect(mapPage).toContain('useSharedMapInteractionMode(slug, { autoLoad: false })')
    expect(mapPage).toContain('useEditableMap(slug, {')
    expect(mapPage).toContain('autoLoad: false')
    expect(mapPage).toContain('interactionMode: mapInteractionMode')
    expect(mapPage).toContain('mapInPrepareMode')
    expect(mapPage).toContain('MAP_INTERACTION_MODES.LIVE_PLAY')
    expect(mapPage).toContain('useLiveTableSnapshotSync({')
    expect(mapPage).toContain('requestAuthoritativeReconciliation: (reason) => requestLiveTableSnapshot(reason)')
    expect(mapPage).toContain('const reconcileLivePlayState = () => reconcileAuthoritativeMap')
    expect(mapPage).toContain('liveSheets.registerAuthoritativeReconciler')
    expect(mapPage).toContain('useLivePlayStateMachine({')
    expect(mapPage).toContain('mapStatus: livePlayMapStatus')
    expect(mapPage).toContain('requestReconciliation: () => livePlayStateMachine.reconcile(reconcileLivePlayState)')
    expect(mapPage).toContain(':live-play-state="livePlayConnectionState"')
    expect(mapPage).toContain(':live-play-status-message="livePlayStatusMessage"')
    expect(mapPage).toContain(':controllable-placement-ids="livePlayActionablePlacementIds"')
    expect(mapPage).toContain('const initiativeControlsEnabled = computed')
    expect(mapPage).toContain(':can-manage-initiative="initiativeControlsEnabled"')
    expect(mapPage).toContain(':can-manage="initiativeControlsEnabled"')
    expect(mapPage).not.toContain('route.query.session')
    expect(mapPage).not.toContain('isSessionModeQueryEnabled')
    expect(mapPage).not.toContain('useSessionMap(')
    expect(mapPage).not.toContain('useSessionMoveTokenDispatch')
    expect(mapPage).not.toContain('useSessionMapSceneCommands')
    expect(mapPage).not.toContain('sessionMoveTokenEnabled')
    expect(mapPage).not.toContain('autosaveEnabled: computed(() => !session')
    expect(mapPage).not.toContain('shouldUseDocumentTokenActions')
    expect(mapPage).not.toContain('useDocumentMapTokenActions')
    expect(mapPage).not.toContain('turnPlacement,')
    expect(mapPage).not.toContain('movePlacement,')
    expect(mapPage).toContain('useMapPageTokenSpawning({')
    expect(mapPage).toContain('livePlayCommands.spawnToken({')
    expect(mapPage).toContain('@select="spawnSheetFromMenu"')
    expect(mapPage).toContain('livePlayCommands.deleteToken({ placementId: id })')
    expect(mapPage).toContain('const dispatchMoveAutomationAuthoritatively: MoveAutomationAuthoritativeDispatchHandler = async (request) => {')
    expect(mapPage).toContain('const result = await livePlayCommands.resolveMove({\n    intent: request.intent,\n    candidateScopePlacementIds: request.candidateScopePlacementIds,\n  })')
    expect(mapPage).toContain('dispatchAuthoritativeMove: dispatchMoveAutomationAuthoritatively')
    expect(mapPage).not.toContain('livePlayCommands.useMove')
    expect(mapPage).toContain('useMapPageTableActionDispatchers({')
    expect(mapPage).not.toContain('const shouldUseTableActionRoutes = () => isPlayer.value')
    expect(mapPage).toContain('const moveTokenFromMoveAutomation = async')
    expect(mapPage).toContain('await livePlayCommands.moveToken({\n    placementId: payload.id,\n    position: payload.position,\n  })')
    expect(mapPage).toContain('moveToken: moveTokenFromMoveAutomation')
    expect(mapPage).toContain('moveDispatchPending,')
    expect(mapPage).toContain('const moveAutomationDispatchInFlight = () => moveDispatchPending.value')
    expect(mapPage).toContain('const openPokeballCaptureFromContext = (payload: { id: string; pokeballName: string }) => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('const cancelActionAutomationTargeting = () => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('dispatchSetInitiative: (payload) => livePlayCommands.setInitiative(payload)')
    expect(mapPage).toContain('dispatchNextInitiative: (payload) => livePlayCommands.nextInitiative(payload)')
    expect(mapPage).toContain('dispatchPreviousInitiative: (payload) => livePlayCommands.previousInitiative(payload)')
    expect(mapPage).toContain('setMapInteractionModeFromAdmin')
    expect(mapPage).not.toContain('const setupEditModeActive = computed(() => isGm.value && adminPanelOpen.value)')
    expect(mapPage).toContain('livePlayCommands.buildTerrainVoxel({ voxel })')
    expect(mapPage).toContain('livePlayCommands.removeTerrainVoxel({ cell })')
    expect(mapPage).toContain('livePlayCommands.placeHazard({ hazard })')
    expect(mapPage).toContain('livePlayCommands.removeHazard({ cell })')
    expect(mapPage).toContain('livePlayCommands.setFieldEffect({')
    expect(mapPage).toContain('livePlayCommands.tickFieldEffectDurations()')
    expect(mapPage).not.toContain('postJson<RecordMoveUsageResponse>')
    expect(mapPage).not.toContain('MAP_API_PATHS.useMove')
    expect(mapPage).not.toContain('recordMoveUsage')
    expect(mapPage).not.toContain('applyRecordedSheetUsage')
    expect(mapPage).not.toContain('unloadFallback: true')

    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    expect(scenePanel).not.toContain('SessionCommandRejectionBanner')
    expect(scenePanel).not.toContain('SessionConnectionStatusBanner')
    expect(scenePanel).not.toContain('SessionPresencePanel')
    expect(scenePanel).not.toContain('refresh-session-snapshot')
    expect(scenePanel).not.toContain('dismiss-session-command-rejection')

    const tokenControls = readSource('src/composables/map-editor/useTokenControls.ts')
    expect(tokenControls).not.toContain('sessionMoveTokenDispatcher')
    expect(tokenControls).not.toContain('sessionTokenControl')
    expect(tokenControls).not.toContain('dispatchMoveToken')
    expect(tokenControls).not.toContain('dispatchTurnToken')

    const mapAccess = readSource('src/composables/map-editor/useMapAccess.ts')
    expect(mapAccess).not.toContain('sessionModeEnabled')
    expect(mapAccess).not.toContain('hasAuthoritativeSessionState')
  })
})
