import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(testDir, '../..')

const readSource = (relativePath: string): string => readFileSync(resolve(repoRoot, relativePath), 'utf8')

describe('map page route authority', () => {
  it('wires clicked live-play movement through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const livePlayTrackedTokenPredictions = ref<Readonly<Record<string, TrackedLivePlayTokenPrediction>>>({})')
    expect(mapPage).toContain('const livePlayTokenCorrectionNoticeController = createLivePlayTokenCorrectionNoticeController()')
    expect(mapPage).toContain('const livePlayTokenCorrectionNotice = livePlayTokenCorrectionNoticeController.notice')
    expect(mapPage).toContain('onCommandAccepted: handleLivePlayCommandAccepted')
    expect(mapPage).toContain('onCommandRejected: handleLivePlayCommandRejected')
    expect(mapPage).toContain('return `Move corrected by the server; ${prediction.tokenLabel} returned to its last confirmed position.`')
    expect(mapPage).toContain('return `Conditions corrected by the server; ${prediction.tokenLabel} returned to its last confirmed conditions.`')
    expect(mapPage).toContain('livePlayTokenCorrectionNoticeController.show({')
    expect(mapPage).toContain("transition.reason !== 'stale-revision'\n    && livePlayTokenCorrectionNoticeController.hasCorrectedOpId(transition.response.opId)")
    expect(mapPage).toContain('if (acceptedPlacementId) livePlayTokenCorrectionNoticeController.clearForPlacement(acceptedPlacementId)')
    expect(mapPage).toContain('livePlayStateMachine.clearCommandError()')
    expect(mapPage).toContain('return playerProfileTokenControlModel.value.notice')
    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeMove = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const predictedMove = newPendingMovePredictionForPlacement(pendingPredictionOpIdsBeforeMove, payload.id)')
    expect(mapPage).toContain('if (predictedMove) {\n    rememberLivePlayPredictedToken(predictedMove, livePlayTokenLabel(payload.id))\n    clearSelection()\n  }')
    expect(mapPage).toContain('const moveWasPredicted = predictedMove !== null\n    if (!moveWasPredicted) clearSelection()')
    expect(mapPage).toContain('if (!result.dispatched) {\n      if (result.opId) forgetLivePlayPredictedToken(result.opId)\n      return\n    }')
    expect(mapPage).toContain('await Promise.resolve(attackOfOpportunityPanel?.provokeMovementAttackOfOpportunity({')
  })

  it('wires clicked live-play facing through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeTurn = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const dispatch = livePlayCommands.turnToken({ placementId: id, facing })')
    expect(mapPage).toContain('const predictedTurn = newPendingTurnPredictionForPlacement(pendingPredictionOpIdsBeforeTurn, id)')
    expect(mapPage).toContain('rememberLivePlayPredictedToken(predictedTurn, livePlayTokenLabel(id))')
    expect(mapPage).toContain('if (result.opId) forgetLivePlayPredictedToken(result.opId)')
    expect(mapPage).toContain('const turnWasPredicted = predictedTurn !== null\n    if (!turnWasPredicted) clearSelection()')
    expect(mapPage).toContain('LIVE_PLAY_COMMAND_TYPES.TURN_TOKEN,')
    expect(mapPage).toContain('turnPlacementForSetupEdit(id)\n    clearSelection()\n    return')
  })

  it('wires token-level live-play prediction affordances into the map renderer', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')
    const tokenRenderer = readSource('src/utils/isometric/tokenRenderer.ts')

    expect(mapPage).toContain('const livePlayPendingPredictionTokenIds = computed(() => Array.from(new Set(')
    expect(mapPage).toContain('const livePlayGlobalTransportPending = computed(() => (')
    expect(mapPage).toContain(':live-play-pending-token-ids="livePlayPendingPredictionTokenIds"')
    expect(mapPage).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId"')
    expect(mapPage).toContain(':live-play-correction-token-ids="livePlayCorrectionTokenIds"')
    expect(mapPage).toContain(':live-play-token-correction-notice="livePlayTokenCorrectionNotice"')
    expect(scenePanel).toContain('class="live-play-token-correction-notice"')
    expect(scenePanel).toContain(':live-play-pending-token-ids="livePlayPendingTokenIds ?? []"')
    expect(scenePanel).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId ?? {}"')
    expect(sceneRenderer).toContain(':live-play-pending-conditions-by-token-id="livePlayPendingConditionsByTokenId ?? {}"')
    expect(sceneRenderer).toContain(':live-play-correction-token-ids="livePlayCorrectionTokenIds ?? []"')
    expect(isometricGrid).toContain('const livePlayPendingTokenIdSet = computed(() => new Set(props.livePlayPendingTokenIds ?? []))')
    expect(isometricGrid).toContain('const renderedPokemons = computed<SpawnedPokemon[]>(() => props.pokemons.map((pokemon) => {')
    expect(isometricGrid).toContain('const pendingConditions = props.livePlayPendingConditionsByTokenId?.[pokemon.id]')
    expect(isometricGrid).toContain('pending: livePlayPendingTokenIdSet.value.has(pokemon.id)')
    expect(isometricGrid).toContain('corrected: livePlayCorrectionTokenIdSet.value.has(pokemon.id)')
    expect(tokenRenderer).toContain('corrected?: boolean')
    expect(tokenRenderer).toContain('corrections temporarily reserve the red invalid ramp for rollback feedback')
  })

  it('wires local token selection and hover into ephemeral presence without changing control authority', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')

    expect(mapPage).toContain('const hoveredPresenceTokenId = ref<string | null>(null)')
    expect(mapPage).toContain('const visiblePresenceTokenIds = computed<readonly string[]>(() => spawnedPokemon.value.map((pokemon) => pokemon.id))')
    expect(mapPage).toContain('visibleTokenIds: visiblePresenceTokenIds')
    expect(mapPage).toContain('presenceTokenIdIfVisible(selectedId.value)')
    expect(mapPage).toContain('presenceTokenIdIfVisible(hoveredPresenceTokenId.value)')
    expect(mapPage).toContain('@hover-pokemon="setHoveredPresenceToken"')
    expect(mapPage).toContain('if (isPlayer.value) clearSelection()')
    expect(scenePanel).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(scenePanel).toContain('@hover-pokemon="emit(\'hover-pokemon\', $event)"')
    expect(sceneRenderer).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(sceneRenderer).toContain('@hover-pokemon="emit(\'hover-pokemon\', $event)"')
    expect(isometricGrid).toContain("(event: 'hover-pokemon', id: string | null): void")
    expect(isometricGrid).toContain("emit('hover-pokemon', nextId)")
    expect(mapPage).toContain('selectPlacement(id)')
    expect(mapPage).not.toContain('remoteTokenLock')
  })

  it('wires ephemeral map pings through presence without map command routes', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')

    expect(mapPage).toContain('const mapPresencePings = mapPresence.pings')
    expect(mapPage).toContain('const placePresencePingFromScene = (payload: { cell: LivePlayPresenceGridCell; label?: unknown }): void => {')
    expect(mapPage).toContain('void mapPresence.placePing(cell, { label: payload.label })')
    expect(mapPage).toContain(':presence-pings="mapPresencePings"')
    expect(mapPage).toContain(':presence-server-time-offset-ms="mapPresenceServerTimeOffsetMs"')
    expect(mapPage).toContain('@place-presence-ping="placePresencePingFromScene"')
    expect(scenePanel).toContain('presencePings?: readonly IsometricPresencePing[]')
    expect(scenePanel).toContain(':presence-pings="presencePings ?? []"')
    expect(scenePanel).toContain("(event: 'place-presence-ping', payload: { cell: LivePlayPresenceGridCell }): void")
    expect(scenePanel).toContain('@place-presence-ping="emit(\'place-presence-ping\', $event)"')
    expect(sceneRenderer).toContain('presencePings?: readonly IsometricPresencePing[]')
    expect(sceneRenderer).toContain(':presence-pings="presencePings ?? []"')
    expect(sceneRenderer).toContain("(event: 'place-presence-ping', payload: { cell: LivePlayPresenceGridCell }): void")
    expect(sceneRenderer).toContain('@place-presence-ping="emit(\'place-presence-ping\', $event)"')
    expect(isometricGrid).toContain('const presencePingRenderer = createPresencePingRenderer(scene)')
    expect(isometricGrid).toContain('const isPresencePingGesture = (event: PointerEvent): boolean => (')
    expect(isometricGrid).toContain("emit('place-presence-ping', { cell })")
    expect(isometricGrid).toContain('!placePresencePingFromPointer(event)')
    expect(mapPage).not.toContain('livePlayCommands.placePing')
    expect(mapPage).not.toContain('mapRevision: mapPresence')
  })

  it('keeps presence transport outside authoritative command blockers and dispatch routes', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const commandOptions = mapPage.slice(
      mapPage.indexOf('const livePlayCommands = useLivePlayCommands({'),
      mapPage.indexOf('livePlayCommandsForPatchAdoption.value = livePlayCommands'),
    )
    const commandBlockerSection = mapPage.slice(
      mapPage.indexOf('const livePlayStateBlocksCommands = computed(() => {'),
      mapPage.indexOf('type LivePlayCommandRejectionNotification'),
    )

    expect(commandOptions).toContain('livePlayCommandBlocked: fundamentalLivePlayCommandBlocked')
    expect(commandOptions).toContain('newCommandBlocked: livePlayRecoveryNewCommandBlocked')
    expect(commandOptions).not.toContain('mapPresence')
    expect(commandBlockerSection).toContain('mapInPrepareMode.value || livePlayStateBlocksCommands.value')
    expect(commandBlockerSection).not.toContain('mapPresence')
    expect(mapPage).toContain('const dispatch = livePlayCommands.turnToken({ placementId: id, facing })')
    expect(mapPage).toContain('const dispatch = livePlayCommands.moveToken({')
    expect(mapPage).toContain('await livePlayCommands.modifyHp({')
    expect(mapPage).toContain('const dispatch = livePlayCommands.modifyConditions({')
    expect(mapPage).not.toContain('presenceCommandBlocked')
  })

  it('publishes compact movement and targeting intent through ephemeral presence', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const targetingIntentHelper = mapPage.slice(
      mapPage.indexOf('const presenceIntentForTargetingOverlay'),
      mapPage.indexOf('const presenceIntentForTargetBranchSelection'),
    )

    expect(mapPage).toContain('const activeOwnPresenceIntent = computed<LivePlayPresenceIntentState>(() => (')
    expect(mapPage).toContain('presenceIntentForTargetingOverlay(actionAutomationTargeting.value)')
    expect(mapPage).toContain('?? presenceIntentForMovementPreview()')
    expect(mapPage).toContain("?? (mapPresence.ownPresence.value.ping ? { kind: 'placing-ping' } : { kind: 'idle' })")
    expect(mapPage).toContain("kind: 'moving-token'")
    expect(mapPage).toContain("kind: 'targeting'")
    expect(mapPage).toContain('sourceTokenId')
    expect(mapPage).toContain('candidateCount')
    expect(mapPage).toContain('targetCount')
    expect(mapPage).toContain('void mapPresence.updateOwnPresence({ intent }, { publish })')
    expect(targetingIntentHelper).not.toContain('moveName')
    expect(targetingIntentHelper).not.toContain('sheet')
    expect(targetingIntentHelper).not.toContain('command')
  })

  it('wires remote shared intent overlays into the isometric renderer without exposing private targets', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')
    const intentOverlays = readSource('src/utils/mapPresenceIntentOverlays.ts')
    const intentRenderer = readSource('src/utils/isometric/presenceIntentRenderer.ts')

    expect(mapPage).toContain("import { buildMapPresenceIntentOverlays } from '~/utils/mapPresenceIntentOverlays'")
    expect(mapPage).toContain('const remotePresenceIntentOverlays = computed(() => buildMapPresenceIntentOverlays(')
    expect(mapPage).toContain('ownPresence: mapPresence.ownPresence.value')
    expect(mapPage).toContain(':presence-intent-overlays="remotePresenceIntentOverlays"')
    expect(scenePanel).toContain('presenceIntentOverlays?: readonly MapPresenceIntentOverlay[]')
    expect(scenePanel).toContain(':presence-intent-overlays="presenceIntentOverlays ?? []"')
    expect(sceneRenderer).toContain('presenceIntentOverlays?: readonly MapPresenceIntentOverlay[]')
    expect(sceneRenderer).toContain(':presence-intent-overlays="presenceIntentOverlays ?? []"')
    expect(isometricGrid).toContain('presenceIntentOverlays?: readonly MapPresenceIntentOverlay[]')
    expect(isometricGrid).toContain('const presenceIntentOverlayRenderer = createPresenceIntentOverlayRenderer(scene)')
    expect(isometricGrid).toContain('syncPresenceIntentOverlays()')
    expect(isometricGrid).toContain('softened: localInteractionSoftensRemoteIntent()')
    expect(intentOverlays).toContain("'moving-token'")
    expect(intentOverlays).toContain("'targeting'")
    expect(intentOverlays).toContain("'measuring'")
    expect(intentOverlays).not.toContain('targetIds')
    expect(intentOverlays).not.toContain('sheetPayload')
    expect(intentRenderer).toContain('pointerEvents = \'none\'')
    expect(intentRenderer).toContain("zIndex = '16'")
  })

  it('wires remote presence token attention into the isometric renderer without token locks', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    const sceneRenderer = readSource('src/components/map/MapSceneRenderer.vue')
    const isometricGrid = readSource('src/components/IsometricGrid.client.vue')
    const tokenRenderer = readSource('src/utils/isometric/tokenRenderer.ts')

    expect(mapPage).toContain("import { buildMapTokenRemoteAttention } from '~/utils/mapPresenceTokenAttention'")
    expect(mapPage).toContain('const remoteTokenAttention = computed(() => buildMapTokenRemoteAttention(')
    expect(mapPage).toContain(':remote-token-attention="remoteTokenAttention"')
    expect(scenePanel).toContain('remoteTokenAttention?: readonly MapTokenRemoteAttention[]')
    expect(scenePanel).toContain(':remote-token-attention="remoteTokenAttention ?? []"')
    expect(sceneRenderer).toContain('remoteTokenAttention?: readonly MapTokenRemoteAttention[]')
    expect(sceneRenderer).toContain(':remote-token-attention="remoteTokenAttention ?? []"')
    expect(isometricGrid).toContain('remoteTokenAttention?: readonly MapTokenRemoteAttention[]')
    expect(isometricGrid).toContain('const remoteTokenAttentionByTokenId = computed(() => new Map(')
    expect(isometricGrid).toContain('remoteAttention: remoteTokenAttentionByTokenId.value.get(pokemon.id)')
    expect(tokenRenderer).toContain('remoteAttention?: PokemonRenderObjectRemoteAttention')
    expect(tokenRenderer).toContain('Remote presence uses a lower-priority accent cage')
    expect(mapPage).not.toContain('remoteTokenLock')
  })

  it('wires the live-play latency debug panel behind an explicit query flag', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const panel = readSource('src/components/map/LivePlayLatencyDebugPanel.vue')

    expect(mapPage).toContain("import LivePlayLatencyDebugPanel from '~/components/map/LivePlayLatencyDebugPanel.vue'")
    expect(mapPage).toContain("const livePlayLatencyDebugEnabled = computed(() => route.query.debugLivePlayLatency === '1')")
    expect(mapPage).toContain('<LivePlayLatencyDebugPanel\n        v-if="livePlayLatencyDebugEnabled"\n        :traces="livePlayCommands.commandTraces.value"\n        :presence-metrics="mapPresenceDebugMetrics"\n      />')
    expect(panel).toContain('Pred → SSE')
    expect(panel).toContain('Pred → HTTP')
    expect(panel).toContain('HTTP → adopt')
    expect(panel).toContain('SSE → adopt')
    expect(panel).toContain('Presence freshness')
    expect(panel).toContain('Active participants')
    expect(panel).toContain("trace.resourceSummary ?? 'resource scope unavailable'")
    expect(panel).toContain("opId.slice(-8)")
    expect(panel).not.toContain('profileId')
    expect(panel).not.toContain('payload.')
  })

  it('wires clear-all hazards through one live-play batch command while setup edit remains local', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const fieldEffectsPanel = readSource('src/components/map/FieldEffectsPanel.vue')
    const hazardControls = readSource('src/components/map/HazardBuilderControls.vue')
    const handlerStart = mapPage.indexOf('const clearAllHazardsFromMenu = async () => {')
    const handlerEnd = mapPage.indexOf('const setWeatherFromMenu = async', handlerStart)

    expect(handlerStart).toBeGreaterThan(-1)
    expect(handlerEnd).toBeGreaterThan(handlerStart)

    const handler = mapPage.slice(handlerStart, handlerEnd)
    expect(handler).toContain('if (isSetupEditMode()) {\n    clearAllHazards()\n    return\n  }')
    expect(handler).toContain("await livePlayCommands.clearHazards({ mode: 'all' })")
    expect(handler).not.toContain('for (const hazard')
    expect(handler).not.toContain('livePlayCommands.removeHazard')
    expect(mapPage).toContain('const livePlayClearHazardsPending = computed(() => (')
    expect(mapPage).toContain('command.commandType === LIVE_PLAY_COMMAND_TYPES.CLEAR_HAZARDS')
    expect(mapPage).toContain(':hazard-clear-pending="livePlayClearHazardsPending"')
    expect(fieldEffectsPanel).toContain(':hazard-clear-pending="hazardClearPending"')
    expect(hazardControls).toContain('hazardClearPending: boolean')
    expect(hazardControls).toContain("{{ hazardClearPending ? 'Clearing hazards…' : 'Clear hazards' }}")
  })

  it('wires clear-all field effects through one live-play batch command while setup edit remains local', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')
    const clearWeatherStart = mapPage.indexOf('const clearWeatherFromMenu = async () => {')
    const clearWeatherEnd = mapPage.indexOf('const toggleTerrainFromMenu = async', clearWeatherStart)
    const clearAllStart = mapPage.indexOf('const clearAllFieldEffectsFromMenu = async () => {')
    const clearAllEnd = mapPage.indexOf('const {\n  buildMode,', clearAllStart)

    expect(clearWeatherStart).toBeGreaterThan(-1)
    expect(clearWeatherEnd).toBeGreaterThan(clearWeatherStart)
    expect(clearAllStart).toBeGreaterThan(-1)
    expect(clearAllEnd).toBeGreaterThan(clearAllStart)

    const clearWeatherHandler = mapPage.slice(clearWeatherStart, clearWeatherEnd)
    const clearAllHandler = mapPage.slice(clearAllStart, clearAllEnd)

    expect(clearWeatherHandler).toContain('if (isSetupEditMode()) {\n    clearWeatherLocally()\n    return\n  }')
    expect(clearWeatherHandler).toContain("const result = await livePlayCommands.clearFieldEffects({ category: 'weather' })")
    expect(clearWeatherHandler).not.toContain('livePlayCommands.removeFieldEffect')
    expect(clearAllHandler).toContain('if (isSetupEditMode()) {\n    clearAllFieldEffectsLocally()\n    return\n  }')
    expect(clearAllHandler).toContain('Clear all active Weather, Terrain, and Room effects?')
    expect(clearAllHandler).toContain("const result = await livePlayCommands.clearFieldEffects({ category: 'all' })")
    expect(clearAllHandler).not.toContain('livePlayCommands.removeFieldEffect')
    expect(clearWeatherHandler).toContain('if (result.dispatched) weatherCoexistNext.value = false')
    expect(clearAllHandler).toContain('if (result.dispatched) weatherCoexistNext.value = false')
    expect(mapPage).toContain("const result = await livePlayCommands.removeFieldEffect({ category: 'weather', kind })")
    expect(mapPage).toContain("if (terrainIsActive(kind)) await livePlayCommands.removeFieldEffect({ category: 'terrain', kind })")
    expect(mapPage).toContain("if (roomIsActive(kind)) await livePlayCommands.removeFieldEffect({ category: 'room', kind })")
  })

  it('uses the saved map route regardless of the session query parameter', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('key: (route) => `map-${routeSlugParam(route.params)}`')
    expect(mapPage).toContain('useLiveSheets({\n  autoHydrate: false,\n  hydrationOwner: `map:${slug}`,\n})')
    expect(mapPage).toContain('useSharedMapInteractionMode(slug, { autoLoad: false })')
    expect(mapPage).toContain('useEditableMap(slug, {')
    expect(mapPage).toContain('autoLoad: false')
    expect(mapPage).toContain('interactionMode: mapInteractionMode')
    expect(mapPage).toContain('mapInPrepareMode')
    expect(mapPage).toContain('MAP_INTERACTION_MODES.LIVE_PLAY')
    expect(mapPage).toContain('useLiveTableSnapshotSync({')
    expect(mapPage).toContain('requestAuthoritativeReconciliation: (reason) => requestLiveTableSnapshot(reason)')
    expect(mapPage).toContain('const reconcileLivePlayState = () => reconcileAuthoritativeMap')
    expect(mapPage).toContain('liveSheets.registerAuthoritativeReconciler')
    expect(mapPage).toContain('useLivePlayStateMachine({')
    expect(mapPage).toContain('mapStatus: livePlayMapStatus')
    expect(mapPage).toContain('requestReconciliation: () => livePlayStateMachine.reconcile(reconcileLivePlayState)')
    expect(mapPage).toContain(':live-play-state="livePlayConnectionState"')
    expect(mapPage).toContain(':live-play-status-message="livePlayStatusMessage"')
    expect(mapPage).toContain(':controllable-placement-ids="livePlayActionablePlacementIds"')
    expect(mapPage).toContain('const initiativeControlsEnabled = computed')
    expect(mapPage).toContain(':can-manage-initiative="initiativeControlsEnabled"')
    expect(mapPage).toContain(':can-manage="initiativeControlsEnabled"')
    expect(mapPage).not.toContain('route.query.session')
    expect(mapPage).not.toContain('isSessionModeQueryEnabled')
    expect(mapPage).not.toContain('useSessionMap(')
    expect(mapPage).not.toContain('useSessionMoveTokenDispatch')
    expect(mapPage).not.toContain('useSessionMapSceneCommands')
    expect(mapPage).not.toContain('sessionMoveTokenEnabled')
    expect(mapPage).not.toContain('autosaveEnabled: computed(() => !session')
    expect(mapPage).not.toContain('shouldUseDocumentTokenActions')
    expect(mapPage).not.toContain('useDocumentMapTokenActions')
    expect(mapPage).not.toContain('turnPlacement,')
    expect(mapPage).not.toContain('movePlacement,')
    expect(mapPage).toContain('useMapPageTokenSpawning({')
    expect(mapPage).toContain('livePlayCommands.spawnToken({')
    expect(mapPage).toContain('@select="spawnSheetFromMenu"')
    expect(mapPage).toContain('livePlayCommands.deleteToken({ placementId: id })')
    expect(mapPage).toContain('const dispatchMoveAutomationAuthoritatively: MoveAutomationAuthoritativeDispatchHandler = async (request) => {')
    expect(mapPage).toContain('const result = await livePlayCommands.resolveMove({\n    intent: request.intent,\n    candidateScopePlacementIds: request.candidateScopePlacementIds,\n  })')
    expect(mapPage).toContain('dispatchAuthoritativeMove: dispatchMoveAutomationAuthoritatively')
    expect(mapPage).not.toContain('livePlayCommands.useMove')
    expect(mapPage).toContain('useMapPageTableActionDispatchers({')
    expect(mapPage).not.toContain('const shouldUseTableActionRoutes = () => isPlayer.value')
    expect(mapPage).toContain('const moveTokenFromMoveAutomation = async')
    expect(mapPage).toContain('await livePlayCommands.moveToken({\n    placementId: payload.id,\n    position: payload.position,\n  })')
    expect(mapPage).toContain('moveToken: moveTokenFromMoveAutomation')
    expect(mapPage).toContain('moveDispatchPending,')
    expect(mapPage).toContain('const moveAutomationDispatchInFlight = () => moveDispatchPending.value')
    expect(mapPage).toContain('const openPokeballCaptureFromContext = (payload: { id: string; pokeballName: string }) => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('const cancelActionAutomationTargeting = () => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('dispatchSetInitiative: (payload) => livePlayCommands.setInitiative(payload)')
    expect(mapPage).toContain('dispatchNextInitiative: (payload) => livePlayCommands.nextInitiative(payload)')
    expect(mapPage).toContain('dispatchPreviousInitiative: (payload) => livePlayCommands.previousInitiative(payload)')
    expect(mapPage).toContain('setMapInteractionModeFromAdmin')
    expect(mapPage).not.toContain('const setupEditModeActive = computed(() => isGm.value && adminPanelOpen.value)')
    expect(mapPage).toContain('useLivePlayTerrainBrushBatcher({')
    expect(mapPage).toContain('dispatchEditTerrainVoxels: (payload) => livePlayCommands.editTerrainVoxels(payload)')
    expect(mapPage).toContain('livePlayTerrainBrushBatcher.queueUpsert(voxel)')
    expect(mapPage).toContain('livePlayTerrainBrushBatcher.queueRemove(cell)')
    expect(mapPage).not.toContain('livePlayCommands.buildTerrainVoxel({ voxel })')
    expect(mapPage).not.toContain('livePlayCommands.removeTerrainVoxel({ cell })')
    expect(mapPage).toContain('useLivePlayHazardBrushBatcher({')
    expect(mapPage).toContain('dispatchEditHazards: (payload) => livePlayCommands.editHazards(payload)')
    expect(mapPage).toContain('dispatchPlaceHazard: (payload) => livePlayCommands.placeHazard(payload)')
    expect(mapPage).toContain('dispatchRemoveHazard: (payload) => livePlayCommands.removeHazard(payload)')
    expect(mapPage).toContain('livePlayHazardBrushBatcher.queueUpsert(hazard)')
    expect(mapPage).toContain('livePlayHazardBrushBatcher.queueRemove(cell)')
    expect(mapPage).toContain('livePlayCommands.placeHazard({ hazard })')
    expect(mapPage).toContain('livePlayCommands.removeHazard({ cell })')
    expect(mapPage).toContain('placeHazard: placeHazardDirect')
    expect(mapPage).toContain('livePlayCommands.setFieldEffect({')
    expect(mapPage).toContain('livePlayCommands.tickFieldEffectDurations()')
    expect(mapPage).not.toContain('postJson<RecordMoveUsageResponse>')
    expect(mapPage).not.toContain('MAP_API_PATHS.useMove')
    expect(mapPage).not.toContain('recordMoveUsage')
    expect(mapPage).not.toContain('applyRecordedSheetUsage')
    expect(mapPage).not.toContain('unloadFallback: true')

    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    expect(scenePanel).not.toContain('SessionCommandRejectionBanner')
    expect(scenePanel).not.toContain('SessionConnectionStatusBanner')
    expect(scenePanel).not.toContain('SessionPresencePanel')
    expect(scenePanel).not.toContain('refresh-session-snapshot')
    expect(scenePanel).not.toContain('dismiss-session-command-rejection')

    const tokenControls = readSource('src/composables/map-editor/useTokenControls.ts')
    expect(tokenControls).not.toContain('sessionMoveTokenDispatcher')
    expect(tokenControls).not.toContain('sessionTokenControl')
    expect(tokenControls).not.toContain('dispatchMoveToken')
    expect(tokenControls).not.toContain('dispatchTurnToken')

    const mapAccess = readSource('src/composables/map-editor/useMapAccess.ts')
    expect(mapAccess).not.toContain('sessionModeEnabled')
    expect(mapAccess).not.toContain('hasAuthoritativeSessionState')
  })
})
