import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(testDir, '../..')

const readSource = (relativePath: string): string => readFileSync(resolve(repoRoot, relativePath), 'utf8')

describe('map page route authority', () => {
  it('wires clicked live-play movement through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const livePlayPredictedMoveOpIds = ref<ReadonlySet<string>>(new Set())')
    expect(mapPage).toContain('const livePlayMoveCorrectionNotice = ref<string | null>(null)')
    expect(mapPage).toContain('onCommandAccepted: handleLivePlayCommandAccepted')
    expect(mapPage).toContain('onCommandRejected: handleLivePlayCommandRejected')
    expect(mapPage).toContain('livePlayMoveCorrectionNotice.value = \'Move corrected by the server; the token returned to its last confirmed position.\'')
    expect(mapPage).toContain('livePlayStateMachine.clearCommandError()')
    expect(mapPage).toContain('return livePlayMoveCorrectionNotice.value ?? playerProfileTokenControlModel.value.notice')
    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeMove = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const predictedMove = newPendingMovePredictionForPlacement(pendingPredictionOpIdsBeforeMove, payload.id)')
    expect(mapPage).toContain('if (predictedMove) {\n    rememberPredictedMoveOpId(predictedMove.opId)\n    clearSelection()\n  }')
    expect(mapPage).toContain('const moveWasPredicted = predictedMove !== null\n    if (!moveWasPredicted) clearSelection()')
    expect(mapPage).toContain('if (!result.dispatched) {\n      if (result.opId) forgetPredictedMoveOpId(result.opId)\n      return\n    }')
    expect(mapPage).toContain('await Promise.resolve(attackOfOpportunityPanel?.provokeMovementAttackOfOpportunity({')
  })

  it('wires clicked live-play facing through local prediction feedback', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('const pendingPredictionOpIdsBeforeTurn = new Set(Object.keys(livePlayCommands.pendingPredictions.value))')
    expect(mapPage).toContain('const dispatch = livePlayCommands.turnToken({ placementId: id, facing })')
    expect(mapPage).toContain('const predictedTurn = newPendingTurnPredictionForPlacement(pendingPredictionOpIdsBeforeTurn, id)')
    expect(mapPage).toContain('if (predictedTurn) clearSelection()')
    expect(mapPage).toContain('const turnWasPredicted = predictedTurn !== null\n    if (!turnWasPredicted) clearSelection()')
    expect(mapPage).toContain('LIVE_PLAY_COMMAND_TYPES.TURN_TOKEN,')
    expect(mapPage).toContain('turnPlacementForSetupEdit(id)\n    clearSelection()\n    return')
  })

  it('uses the saved map route regardless of the session query parameter', () => {
    const mapPage = readSource('src/pages/maps/[slug].vue')

    expect(mapPage).toContain('key: (route) => `map-${routeSlugParam(route.params)}`')
    expect(mapPage).toContain('useLiveSheets({\n  autoHydrate: false,\n  hydrationOwner: `map:${slug}`,\n})')
    expect(mapPage).toContain('useSharedMapInteractionMode(slug, { autoLoad: false })')
    expect(mapPage).toContain('useEditableMap(slug, {')
    expect(mapPage).toContain('autoLoad: false')
    expect(mapPage).toContain('interactionMode: mapInteractionMode')
    expect(mapPage).toContain('mapInPrepareMode')
    expect(mapPage).toContain('MAP_INTERACTION_MODES.LIVE_PLAY')
    expect(mapPage).toContain('useLiveTableSnapshotSync({')
    expect(mapPage).toContain('requestAuthoritativeReconciliation: (reason) => requestLiveTableSnapshot(reason)')
    expect(mapPage).toContain('const reconcileLivePlayState = () => reconcileAuthoritativeMap')
    expect(mapPage).toContain('liveSheets.registerAuthoritativeReconciler')
    expect(mapPage).toContain('useLivePlayStateMachine({')
    expect(mapPage).toContain('mapStatus: livePlayMapStatus')
    expect(mapPage).toContain('requestReconciliation: () => livePlayStateMachine.reconcile(reconcileLivePlayState)')
    expect(mapPage).toContain(':live-play-state="livePlayConnectionState"')
    expect(mapPage).toContain(':live-play-status-message="livePlayStatusMessage"')
    expect(mapPage).toContain(':controllable-placement-ids="livePlayActionablePlacementIds"')
    expect(mapPage).toContain('const initiativeControlsEnabled = computed')
    expect(mapPage).toContain(':can-manage-initiative="initiativeControlsEnabled"')
    expect(mapPage).toContain(':can-manage="initiativeControlsEnabled"')
    expect(mapPage).not.toContain('route.query.session')
    expect(mapPage).not.toContain('isSessionModeQueryEnabled')
    expect(mapPage).not.toContain('useSessionMap(')
    expect(mapPage).not.toContain('useSessionMoveTokenDispatch')
    expect(mapPage).not.toContain('useSessionMapSceneCommands')
    expect(mapPage).not.toContain('sessionMoveTokenEnabled')
    expect(mapPage).not.toContain('autosaveEnabled: computed(() => !session')
    expect(mapPage).not.toContain('shouldUseDocumentTokenActions')
    expect(mapPage).not.toContain('useDocumentMapTokenActions')
    expect(mapPage).not.toContain('turnPlacement,')
    expect(mapPage).not.toContain('movePlacement,')
    expect(mapPage).toContain('useMapPageTokenSpawning({')
    expect(mapPage).toContain('livePlayCommands.spawnToken({')
    expect(mapPage).toContain('@select="spawnSheetFromMenu"')
    expect(mapPage).toContain('livePlayCommands.deleteToken({ placementId: id })')
    expect(mapPage).toContain('const dispatchMoveAutomationAuthoritatively: MoveAutomationAuthoritativeDispatchHandler = async (request) => {')
    expect(mapPage).toContain('const result = await livePlayCommands.resolveMove({\n    intent: request.intent,\n    candidateScopePlacementIds: request.candidateScopePlacementIds,\n  })')
    expect(mapPage).toContain('dispatchAuthoritativeMove: dispatchMoveAutomationAuthoritatively')
    expect(mapPage).not.toContain('livePlayCommands.useMove')
    expect(mapPage).toContain('useMapPageTableActionDispatchers({')
    expect(mapPage).not.toContain('const shouldUseTableActionRoutes = () => isPlayer.value')
    expect(mapPage).toContain('const moveTokenFromMoveAutomation = async')
    expect(mapPage).toContain('await livePlayCommands.moveToken({\n    placementId: payload.id,\n    position: payload.position,\n  })')
    expect(mapPage).toContain('moveToken: moveTokenFromMoveAutomation')
    expect(mapPage).toContain('moveDispatchPending,')
    expect(mapPage).toContain('const moveAutomationDispatchInFlight = () => moveDispatchPending.value')
    expect(mapPage).toContain('const openPokeballCaptureFromContext = (payload: { id: string; pokeballName: string }) => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('const cancelActionAutomationTargeting = () => {\n  if (moveAutomationDispatchInFlight()) return')
    expect(mapPage).toContain('dispatchSetInitiative: (payload) => livePlayCommands.setInitiative(payload)')
    expect(mapPage).toContain('dispatchNextInitiative: (payload) => livePlayCommands.nextInitiative(payload)')
    expect(mapPage).toContain('dispatchPreviousInitiative: (payload) => livePlayCommands.previousInitiative(payload)')
    expect(mapPage).toContain('setMapInteractionModeFromAdmin')
    expect(mapPage).not.toContain('const setupEditModeActive = computed(() => isGm.value && adminPanelOpen.value)')
    expect(mapPage).toContain('livePlayCommands.buildTerrainVoxel({ voxel })')
    expect(mapPage).toContain('livePlayCommands.removeTerrainVoxel({ cell })')
    expect(mapPage).toContain('livePlayCommands.placeHazard({ hazard })')
    expect(mapPage).toContain('livePlayCommands.removeHazard({ cell })')
    expect(mapPage).toContain('livePlayCommands.setFieldEffect({')
    expect(mapPage).toContain('livePlayCommands.tickFieldEffectDurations()')
    expect(mapPage).not.toContain('postJson<RecordMoveUsageResponse>')
    expect(mapPage).not.toContain('MAP_API_PATHS.useMove')
    expect(mapPage).not.toContain('recordMoveUsage')
    expect(mapPage).not.toContain('applyRecordedSheetUsage')
    expect(mapPage).not.toContain('unloadFallback: true')

    const scenePanel = readSource('src/components/map/MapScenePanel.vue')
    expect(scenePanel).not.toContain('SessionCommandRejectionBanner')
    expect(scenePanel).not.toContain('SessionConnectionStatusBanner')
    expect(scenePanel).not.toContain('SessionPresencePanel')
    expect(scenePanel).not.toContain('refresh-session-snapshot')
    expect(scenePanel).not.toContain('dismiss-session-command-rejection')

    const tokenControls = readSource('src/composables/map-editor/useTokenControls.ts')
    expect(tokenControls).not.toContain('sessionMoveTokenDispatcher')
    expect(tokenControls).not.toContain('sessionTokenControl')
    expect(tokenControls).not.toContain('dispatchMoveToken')
    expect(tokenControls).not.toContain('dispatchTurnToken')

    const mapAccess = readSource('src/composables/map-editor/useMapAccess.ts')
    expect(mapAccess).not.toContain('sessionModeEnabled')
    expect(mapAccess).not.toContain('hasAuthoritativeSessionState')
  })
})
