import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(testDir, '../..')
const readSource = (relativePath: string): string => readFileSync(resolve(repoRoot, relativePath), 'utf8')

describe('shop page shells', () => {
  it('renders GM management and player shop library states from the shared /shops page', () => {
    const source = readSource('src/pages/shops/index.vue')

    expect(source).toContain("import AppNavigation from '~/components/AppNavigation.vue'")
    expect(source).toContain("import PlayerShopLibraryCard from '~/components/shops/PlayerShopLibraryCard.vue'")
    expect(source).toContain("import ShopLibraryCard from '~/components/shops/ShopLibraryCard.vue'")
    expect(source).toContain("import { useGmShopLibraryPage } from '~/composables/shops/useGmShopLibraryPage'")
    expect(source).toContain("import { usePlayerShopLibraryPage } from '~/composables/shops/usePlayerShopLibraryPage'")
    expect(source).toContain('const { isGm, isPlayer } = useAuth()')
    expect(source).toContain('const isPlayerShopLibraryEnabled = computed(() => isPlayer.value)')
    expect(source).toContain('useGmShopLibraryPage({ isGm })')
    expect(source).toContain('usePlayerShopLibraryPage({ isEnabled: isPlayerShopLibraryEnabled })')
    expect(source).toContain("title: 'Shops · Rotom Table'")
    expect(source).toContain('<AppNavigation />')
    expect(source).toContain('v-if="isGm"')
    expect(source).toContain('Browse every campaign shop table, including closed and hidden setup documents.')
    expect(source).toContain('@click="createShop"')
    expect(source).toContain("gmShopLibraryStatus === 'loading'")
    expect(source).toContain("gmShopLibraryStatus === 'error'")
    expect(source).toContain("gmShopLibraryStatus === 'empty'")
    expect(source).toContain('<ShopLibraryCard')
    expect(source).toContain('v-for="shop in shops"')
    expect(source).toContain('aria-label="Open shop library"')
    expect(source).toContain("playerShopLibraryStatus === 'loading'")
    expect(source).toContain("playerShopLibraryStatus === 'error'")
    expect(source).toContain("playerShopLibraryStatus === 'empty'")
    expect(source).toContain('No shops are currently open')
    expect(source).toContain('Open player-visible shopfronts will appear here when the GM opens them for players.')
    expect(source).toContain('<PlayerShopLibraryCard')
    expect(source).toContain('v-for="shop in playerShops"')
    expect(source).not.toContain('Return to shop shell')
    expect(source).not.toContain('SHOP_API_PATHS.save')
    expect(source).not.toContain('SHOP_API_PATHS.deleteShop')
  })

  it('loads and renders a player-facing shopfront route with live-play checkout UI', () => {
    const source = readSource('src/pages/shops/[slug].vue')

    expect(source).toContain("import AppNavigation from '~/components/AppNavigation.vue'")
    expect(source).toContain("import ShopfrontCheckoutPanel from '~/components/shops/ShopfrontCheckoutPanel.vue'")
    expect(source).toContain("import ShopfrontEntryList from '~/components/shops/ShopfrontEntryList.vue'")
    expect(source).toContain("import { useShopfrontCheckout } from '~/composables/shops/useShopfrontCheckout'")
    expect(source).toContain("import { useShopfrontPage } from '~/composables/shops/useShopfrontPage'")
    expect(source).toContain("import { routeSlugParam } from '~/utils/routeParams'")
    expect(source).toContain("import { mapEditorPath } from '~/utils/mapRoutes'")
    expect(source).toContain("import { shopCheckoutOriginFromRouteQuery, shopEditorPath, shopLibraryPath } from '~/utils/shopRoutes'")
    expect(source).toContain('const { role, isGm, isPlayer } = useAuth()')
    expect(source).toContain('usePlayerProfiles()')
    expect(source).toContain('const shopSlug = computed(() => routeSlugParam(route.params))')
    expect(source).toContain('const checkoutOrigin = computed(() => shopCheckoutOriginFromRouteQuery(route.query))')
    expect(source).toContain('const mapOriginBackLocation = computed(() => (')
    expect(source).toContain('useShopfrontPage({ slug: shopSlug })')
    expect(source).toContain('useShopfrontCheckout({')
    expect(source).toContain('authRole: role')
    expect(source).toContain('selectedProfileId')
    expect(source).toContain('checkoutOrigin')
    expect(source).toContain('gmPreviewMessage')
    expect(source).toContain('<AppNavigation />')
    expect(source).toContain('Back to map')
    expect(source).toContain('Open GM editor')
    expect(source).toContain("loadStatus === 'loading'")
    expect(source).toContain("loadStatus === 'error'")
    expect(source).toContain('Shopfront unavailable')
    expect(source).toContain('Players can only view shopfronts that are both open and player-visible.')
    expect(source).toContain('<ShopfrontEntryList')
    expect(source).toContain(':quantities="cartQuantities"')
    expect(source).toContain('@update-quantity="setCartQuantity"')
    expect(source).toContain('<ShopfrontCheckoutPanel')
    expect(source).toContain('@checkout="submitCheckout"')
    expect(source).toContain('@retry-outbox-entry="retryOutboxEntry"')
    expect(source).toContain('Browse the shop catalog, choose cart quantities, and buy through server-authoritative live-play checkout commands.')
    expect(source).not.toContain('postJson')
  })

  it('renders a GM-only shop editor that redirects players and wires revision-checked save/delete controls', () => {
    const source = readSource('src/pages/shops/[slug]/edit.vue')

    expect(source).toContain("import AppNavigation from '~/components/AppNavigation.vue'")
    expect(source).toContain("import ShopEntryTable from '~/components/shops/ShopEntryTable.vue'")
    expect(source).toContain("import ShopPurchaseAuditLog from '~/components/shops/ShopPurchaseAuditLog.vue'")
    expect(source).toContain("import { useGmShopEditorPage } from '~/composables/shops/useGmShopEditorPage'")
    expect(source).toContain("import { routeSlugParam } from '~/utils/routeParams'")
    expect(source).toContain("import { shopfrontPath, shopLibraryPath } from '~/utils/shopRoutes'")
    expect(source).toContain('SHOP_DELIVERY_TARGET_KINDS')
    expect(source).toContain('SHOP_PAYMENT_SOURCE_KINDS')
    expect(source).toContain('definePageMeta({')
    expect(source).toContain('middleware: (to) => {')
    expect(source).toContain('const { isPlayer } = useAuth()')
    expect(source).toContain('if (!isPlayer.value) return')
    expect(source).toContain('return navigateTo(slug ? shopfrontPath(slug) : shopLibraryPath(), { replace: true })')
    expect(source).toContain('const { isGm } = useAuth()')
    expect(source).toContain('useGmShopEditorPage({ isGm, slug: shopSlug })')
    expect(source).toContain('GM access required')
    expect(source).toContain("loadStatus === 'loading'")
    expect(source).toContain("loadStatus === 'error'")
    expect(source).toContain('v-else-if="draft"')
    expect(source).toContain('@submit.prevent="saveShop"')
    expect(source).toContain('data-testid="shop-editor-name"')
    expect(source).toContain('data-testid="shop-editor-description"')
    expect(source).toContain('data-testid="shop-editor-player-visible"')
    expect(source).toContain('data-testid="shop-editor-open"')
    expect(source).toContain('data-testid="shop-editor-payment-source"')
    expect(source).toContain('data-testid="shop-editor-delivery-target"')
    expect(source).toContain('<ShopEntryTable :entries="draft.entries" @update:entries="setEntries" />')
    expect(source).toContain('data-testid="shop-editor-gm-notes"')
    expect(source).toContain('<ShopPurchaseAuditLog class="shop-edit-panel panel-card" :entries="draft.purchaseLog ?? []" />')
    expect(source).toContain('Saving sends the loaded revision as <code>expectedRevision</code>')
    expect(source).toContain('data-testid="shop-editor-save"')
    expect(source).toContain('data-testid="shop-editor-reload-conflict"')
    expect(source).toContain('Reload latest shop')
    expect(source).toContain('Reload latest shop before saving again')
    expect(source).toContain('data-testid="shop-editor-delete"')
    expect(source).toContain('@click="deleteCurrentShop"')
  })
})
