import { STRUGGLE_ATTACK_MOVE_NAMES } from '~/utils/struggleMoves'
import { reviewedSingleTargetAttackScript } from '~/utils/move-automation/scriptFactories'
import type { MoveAutomationScript } from '~/types/moveAutomation'

export const SEAMLESS_SINGLE_TARGET_ATTACK_SCRIPT_NAMES = [
  ...STRUGGLE_ATTACK_MOVE_NAMES,
  'Accelerock',
  'Aerial Ace',
  'Air Slash',
  'Aqua Jet',
  'Attack Order',
  'Aura Sphere',
  'Bite',
  'Blaze Kick',
  'Blue Flare',
  'Body Slam',
  'Bolt Strike',
  'Bone Club',
  'Branch Poke',
  'Bullet Punch',
  'Crabhammer',
  'Cross Chop',
  'Dark Pulse',
  'Dragon Breath',
  'Dragon Claw',
  'Dragon Pulse',
  'Drill Peck',
  'Drill Run',
  'Ember',
  'Extrasensory',
  'Extreme Speed',
  'Fairy Wind',
  'False Surrender',
  'Feint Attack',
  'Fire Blast',
  'Fire Punch',
  'Flamethrower',
  'Force Palm',
  'Frustration',
  'Gunk Shot',
  'Headbutt',
  'Heart Stamp',
  'Horn Attack',
  'Hyper Fang',
  'Ice Beam',
  'Ice Punch',
  'Ice Shard',
  'Icicle Crash',
  'Karate Chop',
  'Leafage',
  'Lick',
  'Mach Punch',
  'Magical Leaf',
  'Magnet Bomb',
  'Mega Punch',
  'Needle Arm',
  'Peck',
  'Poison Jab',
  'Poison Sting',
  'Pound',
  'Power Gem',
  'Power Whip',
  'Psycho Cut',
  'Pyro Ball',
  'Quick Attack',
  'Return',
  'Rock Throw',
  'Rolling Kick',
  'Sacred Sword',
  'Scald',
  'Scorching Sands',
  'Seed Bomb',
  'Shadow Punch',
  'Shadow Sneak',
  'Shock Wave',
  'Sludge',
  'Sludge Bomb',
  'Smart Strike',
  'Stone Edge',
  'Thunder Punch',
  'Thunder Shock',
  'Thunderbolt',
  'Vacuum Wave',
  'Vice Grip',
  'Vine Whip',
  'Water Gun',
  'Waterfall',
  'Wing Attack',
  'X-Scissor',
  'Zing Zap',
]

export const STRUGGLE_ATTACK_SCRIPTS: ReadonlyMap<string, MoveAutomationScript> = new Map(
  STRUGGLE_ATTACK_MOVE_NAMES.map((name) => [name, reviewedSingleTargetAttackScript(name)]),
)

export const SEAMLESS_SINGLE_TARGET_ATTACK_SCRIPTS: ReadonlyMap<string, MoveAutomationScript> = new Map(
  SEAMLESS_SINGLE_TARGET_ATTACK_SCRIPT_NAMES.map((name) => [name, reviewedSingleTargetAttackScript(name)]),
)
