import { reviewedSingleTargetStageScript } from '~/utils/move-automation/scriptFactories'
import type { MoveAutomationScript } from '~/types/moveAutomation'

export const REVIEWED_SINGLE_TARGET_STAGE_SCRIPTS: ReadonlyMap<string, MoveAutomationScript> = new Map([
  ['Acid Spray', reviewedSingleTargetStageScript('Acid Spray', [{ key: 'sdef', delta: -2, label: 'Acid Spray lowers Special Defense: -2 Special Defense CS' }])],
  ['Aurora Beam', reviewedSingleTargetStageScript('Aurora Beam', [{ key: 'atk', delta: -1, label: 'Aurora Beam lowers Attack on 18+: -1 Attack CS', threshold: '18+' }])],
  ['Baby-Doll Eyes', reviewedSingleTargetStageScript('Baby-Doll Eyes', [{ key: 'atk', delta: -1, label: 'Baby-Doll Eyes lowers Attack: -1 Attack CS' }])],
  ['Bubble Beam', reviewedSingleTargetStageScript('Bubble Beam', [{ key: 'spd', delta: -1, label: 'Bubble Beam lowers Speed on 18+: -1 Speed CS', threshold: '18+' }])],
  ['Charm', reviewedSingleTargetStageScript('Charm', [{ key: 'atk', delta: -2, label: 'Charm lowers Attack: -2 Attack CS' }])],
  ['Confide', reviewedSingleTargetStageScript('Confide', [{ key: 'satk', delta: -1, label: 'Confide lowers Special Attack: -1 Special Attack CS' }])],
  ['Crunch', reviewedSingleTargetStageScript('Crunch', [{ key: 'def', delta: -1, label: 'Crunch lowers Defense on 17+: -1 Defense CS', threshold: '17+' }])],
  ['Crush Claw', reviewedSingleTargetStageScript('Crush Claw', [{ key: 'def', delta: -1, label: 'Crush Claw lowers Defense on even roll: -1 Defense CS', threshold: 'even roll' }])],
  ['Drum Beating', reviewedSingleTargetStageScript('Drum Beating', [{ key: 'spd', delta: -1, label: 'Drum Beating lowers Speed: -1 Speed CS' }])],
  ['Eerie Impulse', reviewedSingleTargetStageScript('Eerie Impulse', [{ key: 'satk', delta: -2, label: 'Eerie Impulse lowers Special Attack: -2 Special Attack CS' }])],
  ['Energy Ball', reviewedSingleTargetStageScript('Energy Ball', [{ key: 'sdef', delta: -1, label: 'Energy Ball lowers Special Defense on 17+: -1 Special Defense CS', threshold: '17+' }])],
  ['Fake Tears', reviewedSingleTargetStageScript('Fake Tears', [{ key: 'sdef', delta: -2, label: 'Fake Tears lowers Special Defense: -2 Special Defense CS' }])],
  ['Fire Lash', reviewedSingleTargetStageScript('Fire Lash', [{ key: 'def', delta: -1, label: 'Fire Lash lowers Defense: -1 Defense CS' }])],
  ['Flash Cannon', reviewedSingleTargetStageScript('Flash Cannon', [{ key: 'sdef', delta: -1, label: 'Flash Cannon lowers Special Defense on 17+: -1 Special Defense CS', threshold: '17+' }])],
  ['Focus Blast', reviewedSingleTargetStageScript('Focus Blast', [{ key: 'sdef', delta: -1, label: 'Focus Blast lowers Special Defense on 18+: -1 Special Defense CS', threshold: '18+' }])],
  ['Grav Apple', reviewedSingleTargetStageScript('Grav Apple', [{ key: 'def', delta: -1, label: 'Grav Apple lowers Defense: -1 Defense CS' }])],
  ['Iron Tail', reviewedSingleTargetStageScript('Iron Tail', [{ key: 'def', delta: -1, label: 'Iron Tail lowers Defense on 15+: -1 Defense CS', threshold: '15+' }])],
  ['Liquidation', reviewedSingleTargetStageScript('Liquidation', [{ key: 'def', delta: -1, label: 'Liquidation lowers Defense on 17+: -1 Defense CS', threshold: '17+' }])],
  ['Low Sweep', reviewedSingleTargetStageScript('Low Sweep', [{ key: 'spd', delta: -1, label: 'Low Sweep lowers Speed: -1 Speed CS' }])],
  ['Luster Purge', reviewedSingleTargetStageScript('Luster Purge', [{ key: 'sdef', delta: -1, label: 'Luster Purge lowers Special Defense on even roll: -1 Special Defense CS', threshold: 'even roll' }])],
  ['Mist Ball', reviewedSingleTargetStageScript('Mist Ball', [{ key: 'satk', delta: -1, label: 'Mist Ball lowers Special Attack on even roll: -1 Special Attack CS', threshold: 'even roll' }])],
  ['Moonblast', reviewedSingleTargetStageScript('Moonblast', [{ key: 'satk', delta: -1, label: 'Moonblast lowers Special Attack on 15+: -1 Special Attack CS', threshold: '15+' }])],
  ['Mud Bomb', reviewedSingleTargetStageScript('Mud Bomb', [{ key: 'acc', delta: -1, label: 'Mud Bomb lowers Accuracy on 16+: -1 Accuracy CS', threshold: '16+' }])],
  ['Mud Shot', reviewedSingleTargetStageScript('Mud Shot', [{ key: 'spd', delta: -1, label: 'Mud Shot lowers Speed: -1 Speed CS' }])],
  ['Mud-Slap', reviewedSingleTargetStageScript('Mud-Slap', [{ key: 'acc', delta: -1, label: 'Mud-Slap lowers Accuracy: -1 Accuracy CS' }])],
  ['Mystical Fire', reviewedSingleTargetStageScript('Mystical Fire', [{ key: 'satk', delta: -1, label: 'Mystical Fire lowers Special Attack: -1 Special Attack CS' }])],
  ['Night Daze', reviewedSingleTargetStageScript('Night Daze', [{ key: 'acc', delta: -1, label: 'Night Daze lowers Accuracy on 13+: -1 Accuracy CS', threshold: '13+' }])],
  ['Octazooka', reviewedSingleTargetStageScript('Octazooka', [{ key: 'acc', delta: -1, label: 'Octazooka lowers Accuracy on even roll: -1 Accuracy CS', threshold: 'even roll' }])],
  ['Play Nice', reviewedSingleTargetStageScript('Play Nice', [{ key: 'atk', delta: -1, label: 'Play Nice lowers Attack: -1 Attack CS' }])],
  ['Play Rough', reviewedSingleTargetStageScript('Play Rough', [{ key: 'atk', delta: -1, label: 'Play Rough lowers Attack on 17-20: -1 Attack CS', threshold: '17-20' }])],
  ['Razor Shell', reviewedSingleTargetStageScript('Razor Shell', [{ key: 'def', delta: -1, label: 'Razor Shell lowers Defense on even roll: -1 Defense CS', threshold: 'even roll' }])],
  ['Rock Smash', reviewedSingleTargetStageScript('Rock Smash', [{ key: 'def', delta: -1, label: 'Rock Smash lowers Defense on 17+: -1 Defense CS', threshold: '17+' }])],
  ['Rock Tomb', reviewedSingleTargetStageScript('Rock Tomb', [{ key: 'spd', delta: -1, label: 'Rock Tomb lowers Speed: -1 Speed CS' }])],
  ['Scary Face', reviewedSingleTargetStageScript('Scary Face', [{ key: 'spd', delta: -2, label: 'Scary Face lowers Speed: -2 Speed CS' }])],
  ['Shadow Ball', reviewedSingleTargetStageScript('Shadow Ball', [{ key: 'sdef', delta: -1, label: 'Shadow Ball lowers Special Defense on 17+: -1 Special Defense CS', threshold: '17+' }])],
  ['Shadow Bone', reviewedSingleTargetStageScript('Shadow Bone', [{ key: 'def', delta: -1, label: 'Shadow Bone lowers Defense on 17+: -1 Defense CS', threshold: '17+' }])],
  ['Spirit Break', reviewedSingleTargetStageScript('Spirit Break', [{ key: 'satk', delta: -1, label: 'Spirit Break lowers Special Attack: -1 Special Attack CS' }])],
  ['Tickle', reviewedSingleTargetStageScript('Tickle', [
    { key: 'atk', delta: -1, label: 'Tickle lowers Attack: -1 Attack CS' },
    { key: 'def', delta: -1, label: 'Tickle lowers Defense: -1 Defense CS' },
  ])],
])
