import { createHash } from 'node:crypto'
import { stableJsonStringify } from '#shared/automation/stableJson'
import {
  BREEDING_ARCHIVE_MAXIMUM_BYTES,
  BREEDING_ARCHIVE_RECORD_KINDS,
  parseBreedingArchiveImportRequestV1,
  parseBreedingArchiveRecordV1,
  parseBreedingArchiveRestoreReceiptV1,
  parseBreedingArchiveV1,
  parseBreedingCampaignClockArchiveRecordV1,
  parseBreedingLegacyLineageReviewV1,
  parseBreedingMigrationPackageV1,
  parseBreedingSpeciesAcquisitionArchiveRecordV1,
  type BreedingArchiveChunkV1,
  type BreedingArchiveImportRequestV1,
  type BreedingArchivePurpose,
  type BreedingArchiveRecordKind,
  type BreedingArchiveRecordV1,
  type BreedingArchiveRestoreReceiptV1,
  type BreedingArchiveV1,
  type BreedingCampaignClockArchiveRecordV1,
  type BreedingLegacyLineageReviewV1,
  type BreedingMigrationPackageV1,
  type BreedingSpeciesAcquisitionArchiveRecordV1,
} from '#shared/breeding/archives'
import type { BreedingArchiveId } from '#shared/breeding/ids'
import type { BreedingReferenceVersionSnapshotV1 } from '#shared/breeding/readSets'
import type { PokemonBreedingOriginV1 } from '#shared/breeding/lineage'
import type { BreedingIncubationSegmentResultV1 } from '#shared/breeding/incubation'
import { BREEDING_EGG_READY_CORRECTION_REASON_IDS } from '#shared/breeding/readinessCorrection'
import {
  parseAuthoritativeBreedingActorAuthorityV1,
  parseAuthoritativeBreedingAuthorizationReceiptV1,
  parseAuthoritativeBreedingGmOverrideEvidenceV1,
} from './authorization'
import { parseAuthoritativeBreedingCheckRecordV1, parseAuthoritativeBreedingConsentRecordV1, parseAuthoritativeBreedingGmAdjudicationRecordV1, parseAuthoritativeBreedingOptionOfferRecordV1, parseAuthoritativeBreedingRollRecordV1, validateBreedingAdjudicationOfferLink } from './ledgers'
import { parseAuthoritativeBreedingOperationReadSetV1, parseAuthoritativeBreedingReferenceVersionSnapshotV1, validateBreedingOperationReadSetCompleteness } from './readSets'
import { assertBreedingOperationResultMatchesCommand, createBreedingOperationCommandHash, parseAuthoritativeBreedingOperationResultV1 } from './operations'
import { parseAuthoritativeBreedingInheritanceLearningRecordV1, parseAuthoritativePokemonBreedingOriginV1, parseAuthoritativePokemonEggDocumentV1 } from './lineage'
import { parseAuthoritativeBreedingIncubationSegmentResultV1 } from './incubation'
import { deriveBreedingCampaignClockBatchChildOperationIdV1 } from './campaignClockBatch'
import { deriveBreedingHatchSpecialAdjudicationIdV1, deriveBreedingHatchSpecialOfferIdV1 } from './hatchSpecial'
import { parseAuthoritativeBreedingPresentationProjectionV1 } from './projections'
import { parseAuthoritativePokemonEggTransferConsentV1 } from './eggTransfer'
import { parseBreedingSpeciesAcquisitionSourceSettlementV1 } from './speciesAcquisitionIntegration'

export type BreedingArchiveAuthorityErrorCode = 'breeding.archive.hash-mismatch' | 'breeding.archive.oversized' | 'breeding.archive.identity-collision' | 'breeding.archive.cross-link' | 'breeding.archive.unauthorized'
export class BreedingArchiveAuthorityError extends Error { readonly code: BreedingArchiveAuthorityErrorCode; readonly path: string; constructor(code: BreedingArchiveAuthorityErrorCode,path:string,message:string){super(`${path}: ${message}`);this.name='BreedingArchiveAuthorityError';this.code=code;this.path=path} }
const fail=(code:BreedingArchiveAuthorityErrorCode,path:string,message:string):never=>{throw new BreedingArchiveAuthorityError(code,path,message)}
const sha256=(value:unknown):string=>createHash('sha256').update(stableJsonStringify(value)).digest('hex')
const compare=(left:string,right:string):number=>left<right?-1:left>right?1:0
const equalStrict=(left:unknown,right:unknown):boolean=>stableJsonStringify(left)===stableJsonStringify(right)
const strip=(value:Record<string,unknown>,fields:readonly string[]):Record<string,unknown>=>{const result={...value};for(const field of fields)delete result[field];return result}
const verifyDefinitionHash=<Value extends object>(value:Value,hashField:keyof Value,path:string):Value=>{const expected=value[hashField];if(typeof expected!=='string'||sha256(strip(value as Record<string,unknown>,[hashField as string]))!==expected)fail('breeding.archive.hash-mismatch',`${path}.${String(hashField)}`,'does not match the strict record.');return value}
const recordIdentity=(kind:BreedingArchiveRecordKind,record:BreedingArchiveRecordV1):string=>{
  const value=record as any
  if(kind==='project')return value.projectId
  if(kind==='egg')return value.eggId
  if(kind==='consent'||kind==='egg-transfer-consent')return value.consentId
  if(kind==='gm-override')return value.overrideId
  if(kind==='roll')return value.rollRecordId
  if(kind==='check')return value.checkRecordId
  if(kind==='offer')return value.offerId
  if(kind==='adjudication')return value.adjudicationId
  if(kind==='read-set')return value.readSetId
  if(kind==='authorization-receipt')return value.operationId
  if(kind==='operation-command'||kind==='operation-result')return value.operationId
  if(kind==='origin')return value.originId
  if(kind==='inheritance-learning')return value.learningRecordId
  if(kind==='campaign-clock')return 'campaign-clock'
  if(kind==='species-acquisition')return `${value.trainerSheetSlug}/${value.speciesId}`
  if(kind==='species-acquisition-source-settlement')return value.evidence.operationId
  if(kind==='incubation-segment')return value.operationId
  if(kind==='participant-projection'||kind==='owner-projection')return value.projectionDefinitionSha256
  return `${value.aggregateKind}/${value.document?.projectId??value.document?.eggId}/${value.projectionDefinitionSha256}`
}
const authoritativeRecord=(kind:BreedingArchiveRecordKind,value:unknown,path:string):BreedingArchiveRecordV1=>{
  const parsed=parseBreedingArchiveRecordV1(kind,value,path)
  if(kind==='egg')return parseAuthoritativePokemonEggDocumentV1(parsed,path)
  if(kind==='consent')return parseAuthoritativeBreedingConsentRecordV1(parsed,path)
  if(kind==='egg-transfer-consent')return parseAuthoritativePokemonEggTransferConsentV1(parsed,path)
  if(kind==='gm-override')return parseAuthoritativeBreedingGmOverrideEvidenceV1(parsed,path)
  if(kind==='roll')return parseAuthoritativeBreedingRollRecordV1(parsed,path)
  if(kind==='check')return parseAuthoritativeBreedingCheckRecordV1(parsed,path)
  if(kind==='offer')return parseAuthoritativeBreedingOptionOfferRecordV1(parsed,path)
  if(kind==='adjudication')return parseAuthoritativeBreedingGmAdjudicationRecordV1(parsed,path)
  if(kind==='read-set')return parseAuthoritativeBreedingOperationReadSetV1(parsed,path)
  if(kind==='authorization-receipt')return parseAuthoritativeBreedingAuthorizationReceiptV1(parsed,path)
  if(kind==='operation-result')return parseAuthoritativeBreedingOperationResultV1(parsed)
  if(kind==='origin')return parseAuthoritativePokemonBreedingOriginV1(parsed,path)
  if(kind==='inheritance-learning')return parseAuthoritativeBreedingInheritanceLearningRecordV1(parsed,path)
  if(kind==='campaign-clock')return parseAuthoritativeBreedingCampaignClockArchiveRecordV1(parsed,path)
  if(kind==='species-acquisition')return parseAuthoritativeBreedingSpeciesAcquisitionArchiveRecordV1(parsed,path)
  if(kind==='species-acquisition-source-settlement')return parseBreedingSpeciesAcquisitionSourceSettlementV1(parsed,path)
  if(kind==='incubation-segment')return parseAuthoritativeBreedingIncubationSegmentResultV1(parsed,path)
  if(kind==='owner-projection'||kind==='participant-projection'||kind==='gm-projection')return parseAuthoritativeBreedingPresentationProjectionV1(parsed,path) as BreedingArchiveRecordV1
  return parsed
}
const chunksPayload=(archive:BreedingArchiveV1):readonly BreedingArchiveChunkV1[]=>archive.chunks
const archiveDefinition=(archive:BreedingArchiveV1):Record<string,unknown>=>strip(archive as unknown as Record<string,unknown>,['archiveDefinitionSha256'])
const archiveBytes=(archive:BreedingArchiveV1):number=>Buffer.byteLength(stableJsonStringify(archive),'utf8')
export const assertBreedingArchiveEnvelopeByteLengthV1=(byteLength:number):number=>{if(!Number.isSafeInteger(byteLength)||byteLength<0||byteLength>BREEDING_ARCHIVE_MAXIMUM_BYTES)fail('breeding.archive.oversized','archive','must be a nonnegative safe byte length no greater than 64 MiB.');return byteLength}
export const parseAuthoritativeBreedingArchiveV1=(value:unknown,path='archive'):BreedingArchiveV1=>{
  const archive=parseBreedingArchiveV1(value,path)
  parseAuthoritativeBreedingReferenceVersionSnapshotV1(archive.referenceVersions,`${path}.referenceVersions`)
  const identitiesByKind=new Map<BreedingArchiveRecordKind,string[]>()
  for(let i=0;i<archive.chunks.length;i+=1){const chunk=archive.chunks[i]!;const records=chunk.records.map((record,index)=>authoritativeRecord(chunk.recordKind,record,`${path}.chunks[${i}].records[${index}]`));if(sha256(records)!==chunk.recordsSha256)fail('breeding.archive.hash-mismatch',`${path}.chunks[${i}].recordsSha256`,'does not match strict records.');const ids=identitiesByKind.get(chunk.recordKind)??[];ids.push(...records.map(record=>recordIdentity(chunk.recordKind,record)));identitiesByKind.set(chunk.recordKind,ids)}
  for(const [kind,ids] of identitiesByKind)for(let index=1;index<ids.length;index+=1)if(ids[index-1]!>=ids[index]!)fail('breeding.archive.identity-collision',`${path}.${kind}`,'must be unique in canonical record identity order across all chunks.')
  if(sha256(chunksPayload(archive))!==archive.payloadDefinitionSha256)fail('breeding.archive.hash-mismatch',`${path}.payloadDefinitionSha256`,'does not match all chunks.')
  if(sha256(archiveDefinition(archive))!==archive.archiveDefinitionSha256)fail('breeding.archive.hash-mismatch',`${path}.archiveDefinitionSha256`,'does not match the full archive manifest and payload.')
  assertBreedingArchiveEnvelopeByteLengthV1(archiveBytes(archive))
  return archive
}
export const createBreedingArchiveV1=(input:{readonly archiveId:BreedingArchiveId,readonly purpose:BreedingArchivePurpose,readonly campaignIdentitySha256:string,readonly createdAtCampaignMinute:number,readonly rulesetId:string,readonly rulesetDefinitionSha256:string,readonly referenceVersions:BreedingReferenceVersionSnapshotV1,readonly records:Readonly<Partial<Record<BreedingArchiveRecordKind,readonly unknown[]>>>}):BreedingArchiveV1=>{
  const referenceVersions=parseAuthoritativeBreedingReferenceVersionSnapshotV1(input.referenceVersions)
  const chunks:BreedingArchiveChunkV1[]=[]
  const kinds=BREEDING_ARCHIVE_RECORD_KINDS.filter(kind=>(input.records[kind]?.length??0)>0).sort(compare)
  for(const kind of kinds){const records=(input.records[kind]??[]).map((value,index)=>authoritativeRecord(kind,value,`records.${kind}[${index}]`)).sort((left,right)=>compare(recordIdentity(kind,left),recordIdentity(kind,right)));for(let i=1;i<records.length;i+=1)if(recordIdentity(kind,records[i-1]!)===recordIdentity(kind,records[i]!))fail('breeding.archive.identity-collision',`records.${kind}`,'cannot repeat a stable record identity.');for(let offset=0;offset<records.length;offset+=1000){const batch=Object.freeze(records.slice(offset,offset+1000));const index=chunks.length;chunks.push(Object.freeze({schemaVersion:1,chunkId:`chunk:v1:${index.toString().padStart(4,'0')}:${kind}`,index,recordKind:kind,recordCount:batch.length,recordsSha256:sha256(batch),records:batch}))}}
  const payload=Object.freeze(chunks)
  const definition={schemaVersion:1 as const,archiveId:input.archiveId,purpose:input.purpose,campaignIdentitySha256:input.campaignIdentitySha256,createdAtCampaignMinute:input.createdAtCampaignMinute,rulesetId:input.rulesetId,rulesetDefinitionSha256:input.rulesetDefinitionSha256,referenceVersions,chunks:payload,payloadDefinitionSha256:sha256(payload)}
  return parseAuthoritativeBreedingArchiveV1({...definition,archiveDefinitionSha256:sha256(definition)})
}
const unhashedDefinition=(value:object):Record<string,unknown>=>strip(value as Record<string,unknown>,['schemaVersion','definitionSha256'])
export const parseAuthoritativeBreedingCampaignClockArchiveRecordV1=(value:unknown,path='campaignClock'):BreedingCampaignClockArchiveRecordV1=>verifyDefinitionHash(parseBreedingCampaignClockArchiveRecordV1(value,path),'definitionSha256',path)
export const parseAuthoritativeBreedingSpeciesAcquisitionArchiveRecordV1=(value:unknown,path='speciesAcquisition'):BreedingSpeciesAcquisitionArchiveRecordV1=>verifyDefinitionHash(parseBreedingSpeciesAcquisitionArchiveRecordV1(value,path),'definitionSha256',path)
export const createBreedingCampaignClockArchiveRecordV1=(value:Omit<BreedingCampaignClockArchiveRecordV1,'schemaVersion'|'definitionSha256'>):BreedingCampaignClockArchiveRecordV1=>{const definition={schemaVersion:1 as const,...unhashedDefinition(value)};return verifyDefinitionHash(parseBreedingCampaignClockArchiveRecordV1({...definition,definitionSha256:sha256(definition)}),'definitionSha256','campaignClock')}
export const createBreedingSpeciesAcquisitionArchiveRecordV1=(value:Omit<BreedingSpeciesAcquisitionArchiveRecordV1,'schemaVersion'|'definitionSha256'>):BreedingSpeciesAcquisitionArchiveRecordV1=>{const definition={schemaVersion:1 as const,...unhashedDefinition(value)};return verifyDefinitionHash(parseBreedingSpeciesAcquisitionArchiveRecordV1({...definition,definitionSha256:sha256(definition)}),'definitionSha256','speciesAcquisition')}
export const parseAuthoritativeBreedingArchiveImportRequestV1=(value:unknown,path='importRequest'):BreedingArchiveImportRequestV1=>verifyDefinitionHash(parseBreedingArchiveImportRequestV1(value,path),'definitionSha256',path)
export const createBreedingArchiveImportRequestV1=(value:Omit<BreedingArchiveImportRequestV1,'schemaVersion'|'definitionSha256'>):BreedingArchiveImportRequestV1=>{const definition={schemaVersion:1 as const,...unhashedDefinition(value)};return parseAuthoritativeBreedingArchiveImportRequestV1({...definition,definitionSha256:sha256(definition)})}
export const parseAuthoritativeBreedingArchiveRestoreReceiptV1=(value:unknown,path='restoreReceipt'):BreedingArchiveRestoreReceiptV1=>verifyDefinitionHash(parseBreedingArchiveRestoreReceiptV1(value,path),'definitionSha256',path)
export const createBreedingArchiveRestoreReceiptV1=(value:Omit<BreedingArchiveRestoreReceiptV1,'schemaVersion'|'definitionSha256'>):BreedingArchiveRestoreReceiptV1=>{const clean=unhashedDefinition(value) as unknown as Omit<BreedingArchiveRestoreReceiptV1,'schemaVersion'|'definitionSha256'>;const definition={schemaVersion:1 as const,...clean,recordCounts:Object.freeze([...clean.recordCounts].sort((left,right)=>compare(left.recordKind,right.recordKind)))};return parseAuthoritativeBreedingArchiveRestoreReceiptV1({...definition,definitionSha256:sha256(definition)})}
const legacyMoveFieldsDefinition=(value:Pick<BreedingLegacyLineageReviewV1,'legacyEggMoveIds'|'legacyInheritedMoveIds'>):Record<string,unknown>=>({legacyEggMoveIds:value.legacyEggMoveIds,legacyInheritedMoveIds:value.legacyInheritedMoveIds})
export const parseAuthoritativeBreedingLegacyLineageReviewV1=(value:unknown,path='legacyReview'):BreedingLegacyLineageReviewV1=>{const review=verifyDefinitionHash(parseBreedingLegacyLineageReviewV1(value,path),'definitionSha256',path);if(sha256(legacyMoveFieldsDefinition(review))!==review.legacyFieldsDefinitionSha256)fail('breeding.archive.hash-mismatch',`${path}.legacyFieldsDefinitionSha256`,'does not match the exact compatibility-only legacy Move fields.');return review}
export const createBreedingLegacyLineageReviewV1=(value:Omit<BreedingLegacyLineageReviewV1,'schemaVersion'|'definitionSha256'|'legacyFieldsDefinitionSha256'> & {readonly legacyFieldsDefinitionSha256?:string}):BreedingLegacyLineageReviewV1=>{const clean=unhashedDefinition(value) as unknown as Omit<BreedingLegacyLineageReviewV1,'schemaVersion'|'definitionSha256'>;const moveFields={legacyEggMoveIds:Object.freeze([...clean.legacyEggMoveIds].sort(compare)),legacyInheritedMoveIds:Object.freeze([...clean.legacyInheritedMoveIds].sort(compare))};const definition={schemaVersion:1 as const,...clean,...moveFields,legacyFieldsDefinitionSha256:sha256(legacyMoveFieldsDefinition(moveFields))};return parseAuthoritativeBreedingLegacyLineageReviewV1({...definition,definitionSha256:sha256(definition)})}
export const parseAuthoritativeBreedingMigrationPackageV1=(value:unknown,path='migration'):BreedingMigrationPackageV1=>{const migration=parseBreedingMigrationPackageV1(value,path);migration.legacyLineageReviews.forEach((review,index)=>parseAuthoritativeBreedingLegacyLineageReviewV1(review,`${path}.legacyLineageReviews[${index}]`));return verifyDefinitionHash(migration,'definitionSha256',path)}
export const createBreedingMigrationPackageV1=(value:Omit<BreedingMigrationPackageV1,'schemaVersion'|'definitionSha256'>):BreedingMigrationPackageV1=>{const clean=unhashedDefinition(value) as unknown as Omit<BreedingMigrationPackageV1,'schemaVersion'|'definitionSha256'>;const definition={schemaVersion:1 as const,...clean,sourceArtifacts:Object.freeze([...clean.sourceArtifacts].sort((left,right)=>compare(left.sourceId,right.sourceId))),legacyLineageReviews:Object.freeze([...clean.legacyLineageReviews].sort((left,right)=>compare(left.reviewId,right.reviewId)))};return parseAuthoritativeBreedingMigrationPackageV1({...definition,definitionSha256:sha256(definition)})}
export const validateBreedingMigrationPackageForApplicationV1=(input:{readonly migration:unknown,readonly observedSourceArtifacts:readonly {readonly sourceId:string,readonly contentSha256:string,readonly sizeBytes:number,readonly privacyClass:'campaign-private'|'reviewed-reference'}[],readonly expectedMigrationToolDefinitionSha256:string,readonly validateReviewerEvidence:(definitionSha256:string)=>boolean,readonly validateLegacyReviewEvidence:(review:BreedingLegacyLineageReviewV1)=>boolean,readonly resultArchive:unknown|null}):{readonly migration:BreedingMigrationPackageV1,readonly resultArchive:BreedingArchiveV1|null}=>{const migration=parseAuthoritativeBreedingMigrationPackageV1(input.migration);const observed=[...input.observedSourceArtifacts].sort((left,right)=>compare(left.sourceId,right.sourceId));if(!equalStrict(migration.sourceArtifacts,observed))fail('breeding.archive.cross-link','migration.sourceArtifacts','must exactly match every observed source hash, size, and privacy class.');if(migration.migrationToolDefinitionSha256!==input.expectedMigrationToolDefinitionSha256||!input.validateReviewerEvidence(migration.reviewerEvidenceDefinitionSha256))fail('breeding.archive.unauthorized','migration.reviewerEvidenceDefinitionSha256','must bind the reviewed current migration tool and reviewer evidence.');for(const review of migration.legacyLineageReviews)if(!input.validateLegacyReviewEvidence(review))fail('breeding.archive.unauthorized','migration.legacyLineageReviews','must bind every decision to authoritative GM adjudication evidence.');if(migration.resultArchiveDefinitionSha256===null){if(input.resultArchive!==null)fail('breeding.archive.cross-link','migration.resultArchiveDefinitionSha256','does not permit a resulting archive.');return Object.freeze({migration,resultArchive:null})}const result=parseAuthoritativeBreedingArchiveV1(input.resultArchive);if(result.purpose!=='campaign-backup'||result.archiveDefinitionSha256!==migration.resultArchiveDefinitionSha256||result.campaignIdentitySha256!==migration.sourceCampaignIdentitySha256)fail('breeding.archive.cross-link','migration.resultArchiveDefinitionSha256','must bind the exact same-campaign v1 backup result.');return Object.freeze({migration,resultArchive:result})}
const recordsOf=<Kind extends BreedingArchiveRecordKind>(archive:BreedingArchiveV1,kind:Kind):BreedingArchiveRecordV1[]=>archive.chunks.filter(chunk=>chunk.recordKind===kind).flatMap(chunk=>[...chunk.records])
const archiveCounts=(archive:BreedingArchiveV1):readonly {readonly recordKind:BreedingArchiveRecordKind,readonly count:number}[]=>Object.freeze([...archive.chunks.reduce((map,chunk)=>map.set(chunk.recordKind,(map.get(chunk.recordKind)??0)+chunk.recordCount),new Map<BreedingArchiveRecordKind,number>()).entries()].map(([recordKind,count])=>Object.freeze({recordKind,count})).sort((left,right)=>compare(left.recordKind,right.recordKind)))
const validateBackupLinks=(archive:BreedingArchiveV1):void=>{
  const clocks=recordsOf(archive,'campaign-clock') as BreedingCampaignClockArchiveRecordV1[];if(clocks.length!==1||clocks[0]!.campaignMinute!==archive.createdAtCampaignMinute)fail('breeding.archive.cross-link','archive.chunks','campaign backup requires exactly one clock at the archive checkpoint minute.')
  const projects=recordsOf(archive,'project') as any[];const eggs=recordsOf(archive,'egg') as any[];const origins=recordsOf(archive,'origin') as PokemonBreedingOriginV1[];const learning=recordsOf(archive,'inheritance-learning') as any[];const acquisitions=recordsOf(archive,'species-acquisition') as BreedingSpeciesAcquisitionArchiveRecordV1[];const transferConsents=recordsOf(archive,'egg-transfer-consent') as any[];const overrides=recordsOf(archive,'gm-override') as any[];const sourceSettlements=recordsOf(archive,'species-acquisition-source-settlement') as any[]
  const commands=recordsOf(archive,'operation-command') as any[];const results=recordsOf(archive,'operation-result') as any[];const readSets=recordsOf(archive,'read-set') as any[];const receipts=recordsOf(archive,'authorization-receipt') as any[];const rolls=recordsOf(archive,'roll') as any[];const checks=recordsOf(archive,'check') as any[];const offers=recordsOf(archive,'offer') as any[];const consents=recordsOf(archive,'consent') as any[];const adjudications=recordsOf(archive,'adjudication') as any[];const incubationSegments=recordsOf(archive,'incubation-segment') as BreedingIncubationSegmentResultV1[]
  const projectMap=new Map(projects.map(value=>[value.projectId,value]));const eggMap=new Map(eggs.map(value=>[value.eggId,value]));const originMap=new Map(origins.map(value=>[value.originId,value]));const commandMap=new Map(commands.map(value=>[value.operationId,value]));const resultMap=new Map(results.map(value=>[value.operationId,value]));const readSetMap=new Map(readSets.map(value=>[value.operationId,value]));const receiptMap=new Map(receipts.map(value=>[value.operationId,value]));const rollMap=new Map(rolls.map(value=>[value.rollRecordId,value]));const checkMap=new Map(checks.map(value=>[value.checkRecordId,value]));const offerMap=new Map(offers.map(value=>[value.offerId,value]));const adjudicationMap=new Map(adjudications.map(value=>[value.adjudicationId,value]));const transferConsentMap=new Map(transferConsents.map(value=>[value.consentId,value]));const acquisitionMap=new Map(acquisitions.map(value=>[`${value.trainerSheetSlug}/${value.speciesId}`,value]));const sourceSettlementMap=new Map(sourceSettlements.map(value=>[value.evidence.operationId,value]));const overrideMap=new Map(overrides.map(value=>[value.overrideId,value]))
  const requireCommand=(operationId:string|null,commandSha256:string|null,path:string):void=>{if(operationId===null)return;const command=commandMap.get(operationId);if(!command||(commandSha256!==null&&createBreedingOperationCommandHash(command)!==commandSha256))fail('breeding.archive.cross-link',path,'must bind one archived operation command and its full command hash.')}
  if(commands.length!==results.length||commands.length!==readSets.length||commands.length!==receipts.length)fail('breeding.archive.cross-link','operationEvidence','must contain one result, complete read set, and authorization receipt per command.')
  for(const command of commands){const commandHash=createBreedingOperationCommandHash(command);const result=resultMap.get(command.operationId);const readSet=readSetMap.get(command.operationId);const receipt=receiptMap.get(command.operationId);if(!result||!readSet||!receipt||readSet.commandSha256!==commandHash||readSet.commandKind!==command.commandKind||receipt.commandSha256!==commandHash||receipt.commandKind!==command.commandKind||receipt.readSetDefinitionSha256!==readSet.definitionSha256||receipt.gmOverrideIds.some((id:string)=>overrideMap.get(id)?.operationId!==command.operationId))fail('breeding.archive.cross-link','operationEvidence','must link exact command, read-set, authorization, override, and terminal result evidence.');try{validateBreedingOperationReadSetCompleteness(command,readSet)}catch{fail('breeding.archive.cross-link','operationEvidence.readSet','must retain one complete immutable read set for the exact archived command.')}assertBreedingOperationResultMatchesCommand(command,result)}
  for(const value of overrides){const command=commandMap.get(value.operationId);const receipt=receiptMap.get(value.operationId);if(!command||createBreedingOperationCommandHash(command)!==value.commandSha256||!receipt?.gmOverrideIds.includes(value.overrideId)||receipt.actorAuthorityDefinitionSha256!==value.actorAuthorityDefinitionSha256||receipt.evaluatedAtCampaignMinute!==value.createdAtCampaignMinute||receipt.securityPolicyDefinitionSha256!==value.securityPolicyDefinitionSha256)fail('breeding.archive.cross-link','gmOverride.operationId','must link one archived command and its exact actor-, time-, policy-, and authorization-bound receipt.')}
  requireCommand(clocks[0]!.lastOperationId,null,'campaignClock.lastOperationId')
  for(const project of projects){requireCommand(project.lastOperationId,null,'project.lastOperationId');if(project.producedEggId!==null&&(!eggMap.has(project.producedEggId)||eggMap.get(project.producedEggId)?.source.kind!=='breeding'||eggMap.get(project.producedEggId)?.source.projectId!==project.projectId))fail('breeding.archive.cross-link','project.producedEggId','must link one archived breeding Egg back to the project.');if(project.check!==null){const check=checkMap.get(project.check.checkRecordId);if(!check||check.projectId!==project.projectId||check.outcome!==project.check.outcome||check.resolvedAtCampaignMinute!==project.check.resolvedAtCampaignMinute)fail('breeding.archive.cross-link','project.check','must link its exact archived immutable check record.')}}
  const childSlugs=new Set<string>();for(const egg of eggs){
    requireCommand(egg.lastOperationId,null,'egg.lastOperationId');requireCommand(egg.incubation.readyOperationId,null,'egg.incubation.readyOperationId');requireCommand(egg.incubation.pauseOperationId,null,'egg.incubation.pauseOperationId');requireCommand(egg.hatchOperationId,null,'egg.hatchOperationId');
    if(egg.incubation.readinessKind==='gm-mark-ready'){
      const command=commandMap.get(egg.incubation.readyOperationId);const result=resultMap.get(egg.incubation.readyOperationId)
      if(!command||command.commandKind!=='mark-egg-ready'||command.payload.eggId!==egg.eggId||!BREEDING_EGG_READY_CORRECTION_REASON_IDS.some(reasonId=>reasonId===command.payload.reasonId)||!result?.ok||result.outcomeKind!=='egg-ready'||result.committedAtCampaignMinute!==egg.incubation.readyAtCampaignMinute||!result.aggregateRefs.some((value:any)=>value.kind==='pokemon-egg'&&value.id===egg.eggId&&value.revision<=egg.revision))fail('breeding.archive.cross-link','egg.incubation.readyOperationId','GM readiness must retain its accepted typed correction command, reason, time, and Egg revision result.')
    }
    if(egg.special.rollRecordId!==null){const roll=rollMap.get(egg.special.rollRecordId);if(!roll||roll.purpose!=='hatch-special-d100'||roll.target.kind!=='pokemon-egg'||roll.target.eggId!==egg.eggId||roll.total!==egg.special.rollTotal||roll.operationId!==egg.hatchOperationId)fail('breeding.archive.cross-link','egg.special.rollRecordId','must link the Egg exact single persisted hatch-special d100.');if(rolls.filter(value=>value.purpose==='hatch-special-d100'&&value.target.kind==='pokemon-egg'&&value.target.eggId===egg.eggId).length!==1)fail('breeding.archive.identity-collision','egg.special.rollRecordId','an Egg must retain exactly one hatch-special roll.')}
    if(egg.special.state==='pending-adjudication'||egg.special.state==='resolved'){const adjudicationId=egg.hatchOperationId?deriveBreedingHatchSpecialAdjudicationIdV1(egg.hatchOperationId,egg.eggId):null;const offerId=egg.hatchOperationId?deriveBreedingHatchSpecialOfferIdV1(egg.hatchOperationId,egg.eggId):null;const adjudication=adjudicationId?adjudicationMap.get(adjudicationId):null;const offer=offerId?offerMap.get(offerId):null;if(!adjudication||!offer)fail('breeding.archive.cross-link','egg.special.adjudicationId','must retain the deterministic hatch-special adjudication and bounded offer.');validateBreedingAdjudicationOfferLink(adjudication,offer);if(egg.special.state==='pending-adjudication'&&(adjudication.status!=='pending'||offer.status!=='active'||adjudication.target.revision!==egg.revision)||egg.special.state==='resolved'&&(adjudication.status!=='resolved'||offer.status!=='consumed'||egg.special.adjudicationId!==adjudication.adjudicationId||egg.special.outcomeId!==offer.options.find((value:any)=>value.optionId===offer.selectedOptionId)?.canonicalValueId))fail('breeding.archive.cross-link','egg.special.adjudicationId','must match the current pending or resolved hatch-special ledger state.')}
    if(egg.source.kind==='breeding'&&!projectMap.has(egg.source.projectId))fail('breeding.archive.cross-link','egg.source.projectId','must link an archived project.');if(egg.childSheetSlug!==null){if(childSlugs.has(egg.childSheetSlug))fail('breeding.archive.identity-collision','egg.childSheetSlug','one child sheet cannot be linked from multiple Eggs.');childSlugs.add(egg.childSheetSlug)}
  }
  const originEggs=new Set<string>();const originChildren=new Set<string>();for(const origin of origins){const sourceEgg=eggMap.get(origin.eggId);if(!sourceEgg||sourceEgg.status!=='hatched'||sourceEgg.childSheetSlug!==origin.childSheetSlug||originEggs.has(origin.eggId)||originChildren.has(origin.childSheetSlug))fail('breeding.archive.cross-link','origin.eggId','must uniquely link the archived settled Egg and child.');originEggs.add(origin.eggId);originChildren.add(origin.childSheetSlug);requireCommand(origin.hatchOperationId,null,'origin.hatchOperationId');requireCommand(origin.settlementOperationId,null,'origin.settlementOperationId');for(const record of origin.inheritanceLearningRecords)requireCommand(record.operationId,null,'origin.inheritanceLearningRecords.operationId')}
  for(const egg of eggs)if(egg.status==='hatched'&&!originEggs.has(egg.eggId))fail('breeding.archive.cross-link','egg.childSheetSlug','every hatched Egg must link exactly one immutable origin.')
  for(const value of learning){if(!originMap.has(value.originId)||originMap.get(value.originId)?.eggId!==value.eggId||originMap.get(value.originId)?.childSheetSlug!==value.childSheetSlug)fail('breeding.archive.cross-link','inheritanceLearning.originId','must link the archived immutable origin and child.');requireCommand(value.operationId,null,'inheritanceLearning.operationId')}
  for(const value of acquisitions){if(value.sourceEggId!==null&&!eggMap.has(value.sourceEggId))fail('breeding.archive.cross-link','speciesAcquisition.sourceEggId','must link an archived Egg.');if(value.sourceKind==='hatch')requireCommand(value.operationId,null,'speciesAcquisition.operationId');else{const settlement=sourceSettlementMap.get(value.operationId);if(!settlement||settlement.outcome!=='first-acquisition-rewarded'||settlement.acquisitionDefinitionSha256!==value.definitionSha256||settlement.evidence.sourceKind!==value.sourceKind||settlement.evidence.trainerSheetSlug!==value.trainerSheetSlug||settlement.evidence.speciesId!==value.speciesId||settlement.evidence.campaignMinute!==value.firstAcquiredAtCampaignMinute)fail('breeding.archive.cross-link','speciesAcquisition.operationId','external first acquisition must link its exact terminal source settlement.')}}
  for(const value of sourceSettlements){const acquisition=acquisitionMap.get(`${value.evidence.trainerSheetSlug}/${value.evidence.speciesId}`);if(!acquisition||value.acquisitionDefinitionSha256!==acquisition.definitionSha256||commandMap.has(value.evidence.operationId)||(value.outcome==='first-acquisition-rewarded'&&acquisition.operationId!==value.evidence.operationId))fail('breeding.archive.cross-link','speciesAcquisitionSourceSettlement.evidence','must link one immutable acquisition without forging a Breeding command.')}
  for(const value of transferConsents){const egg=eggMap.get(value.eggId);if(!egg||egg.revision<value.eggRevision)fail('breeding.archive.cross-link','eggTransferConsent.eggId','must link one archived Egg at or after the consent revision.');if(value.role==='recipient-acceptance'){const source=transferConsentMap.get(value.counterpartConsentId);if(!source||source.role!=='source-gift'||source.eggId!==value.eggId||source.eggRevision!==value.eggRevision||source.sourceTrainerSlug!==value.sourceTrainerSlug||source.destinationTrainerSlug!==value.destinationTrainerSlug||source.expiresAtCampaignMinute!==value.expiresAtCampaignMinute)fail('breeding.archive.cross-link','eggTransferConsent.counterpartConsentId','must link the exact archived source-gift consent.')}if(value.settlementOperationId!==null){const command=commandMap.get(value.settlementOperationId);const expectedKind=value.status==='consumed'?'transfer-egg':'settle-egg-transfer-consent';if(!command||command.commandKind!==expectedKind)fail('breeding.archive.cross-link','eggTransferConsent.settlementOperationId','must link the typed archived settlement command.')}}
  for(const value of rolls)requireCommand(value.operationId,value.commandSha256,'roll.operationId')
  for(const value of checks){requireCommand(value.operationId,value.commandSha256,'check.operationId');if(!projectMap.has(value.projectId)||!rollMap.has(value.rollRecordId))fail('breeding.archive.cross-link','check.projectId','must link its archived project and injected roll.')}
  for(const value of offers){requireCommand(value.issuedOperationId,value.issuedCommandSha256,'offer.issuedOperationId');requireCommand(value.settlementOperationId,value.settlementCommandSha256,'offer.settlementOperationId')}
  for(const value of consents){if(!projectMap.has(value.projectId))fail('breeding.archive.cross-link','consent.projectId','must link an archived project.');requireCommand(value.grantOperationId,value.grantCommandSha256,'consent.grantOperationId');requireCommand(value.settlementOperationId,value.settlementCommandSha256,'consent.settlementOperationId')}
  for(const value of adjudications){requireCommand(value.createdOperationId,value.createdCommandSha256,'adjudication.createdOperationId');requireCommand(value.settlementOperationId,value.settlementCommandSha256,'adjudication.settlementOperationId');if(value.adjudicationKind==='hatch-special-result'){const offer=value.offerId?offerMap.get(value.offerId):null;const egg=value.target.kind==='pokemon-egg'?eggMap.get(value.target.eggId):null;if(!offer||!egg)fail('breeding.archive.cross-link','adjudication.offerId','hatch-special adjudication must link its bounded offer and archived Egg.');validateBreedingAdjudicationOfferLink(value,offer)}}
  const incubationSegmentMap=new Map(incubationSegments.map(value=>[value.operationId,value]));for(const segment of incubationSegments){const command=commandMap.get(segment.operationId);const result=resultMap.get(segment.operationId);const egg=eggMap.get(segment.eggId);if(!command||command.commandKind!==segment.commandKind||command.payload.eggId!==segment.eggId||!result?.ok||result.outcomeKind!==(segment.commandKind==='advance-egg-incubation'?'egg-progressed':'egg-pause-set')||!result.aggregateRefs.some((value:any)=>value.kind==='pokemon-egg'&&value.id===segment.eggId&&value.revision===segment.eggRevisionAfter)||!egg||egg.revision<segment.eggRevisionAfter)fail('breeding.archive.cross-link','incubationSegment.operationId','must link its accepted command, exact Egg revision result, and current archived Egg.')}for(const command of commands){const result=resultMap.get(command.operationId);if(result?.ok&&(command.commandKind==='advance-egg-incubation'||command.commandKind==='set-egg-incubation-pause')&&!incubationSegmentMap.has(command.operationId))fail('breeding.archive.cross-link','incubationSegment.operationId','every accepted incubation mutation must retain its exact segment result.')}
  for(const parent of commands){
    if(parent.commandKind!=='advance-campaign-clock'||parent.scopes.length===1)continue
    const parentResult=resultMap.get(parent.operationId)
    const eggScopes=parent.scopes.slice(1)
    if(!parentResult?.ok)continue
    const clockRef=parentResult.aggregateRefs.find((value:any)=>value.kind==='campaign-clock'&&value.id==='campaign-clock')
    if(!clockRef)fail('breeding.archive.cross-link','clockBatch.aggregateRefs','accepted clock batch must retain its exact clock revision result.')
    for(const scope of eggScopes){
      if(scope.kind!=='pokemon-egg')fail('breeding.archive.cross-link','clockBatch.scopes','clock incubation batch may contain only Egg dependent scopes.')
      const childId=deriveBreedingCampaignClockBatchChildOperationIdV1(parent.operationId,scope.eggId)
      const child=commandMap.get(childId);const childResult=resultMap.get(childId)
      if(!child||child.commandKind!=='advance-egg-incubation'||child.payload.eggId!==scope.eggId||child.payload.throughClockRevision!==clockRef.revision||child.payload.throughCampaignMinute!==parent.payload.targetCampaignMinute||child.scopes.length!==1||!equalStrict(child.scopes[0],scope)||!childResult)fail('breeding.archive.cross-link','clockBatch.scopes','every accepted parent Egg scope must retain its deterministic terminal incubation child command and target checkpoint.')
    }
  }
}
export const validateBreedingCampaignBackupIntegrityV1=(value:unknown):BreedingArchiveV1=>{const archive=parseAuthoritativeBreedingArchiveV1(value);if(archive.purpose!=='campaign-backup')fail('breeding.archive.cross-link','archive.purpose','integrity validation requires a campaign-backup archive.');validateBackupLinks(archive);return archive}
export const validateBreedingArchiveImportV1=(input:{readonly archive:unknown,readonly request:unknown,readonly actorAuthority:unknown,readonly currentReferenceVersions:unknown,readonly currentArchiveDefinitionSha256:string|null,readonly validateRecordDependencies:(kind:BreedingArchiveRecordKind,record:BreedingArchiveRecordV1)=>boolean}):{readonly archive:BreedingArchiveV1,readonly request:BreedingArchiveImportRequestV1,readonly recordCounts:readonly {readonly recordKind:BreedingArchiveRecordKind,readonly count:number}[]}=>{
  const archive=parseAuthoritativeBreedingArchiveV1(input.archive);const request=parseAuthoritativeBreedingArchiveImportRequestV1(input.request);const actor=parseAuthoritativeBreedingActorAuthorityV1(input.actorAuthority);const references=parseAuthoritativeBreedingReferenceVersionSnapshotV1(input.currentReferenceVersions)
  if(request.archiveId!==archive.archiveId||request.archiveDefinitionSha256!==archive.archiveDefinitionSha256)fail('breeding.archive.hash-mismatch','request.archiveDefinitionSha256','must bind the exact archive.')
  if(request.actorAuthorityDefinitionSha256!==actor.definitionSha256||request.requestedAtCampaignMinute!==actor.evaluatedAtCampaignMinute||archive.createdAtCampaignMinute>request.requestedAtCampaignMinute)fail('breeding.archive.unauthorized','request.actorAuthorityDefinitionSha256','must bind the current authenticated actor after archive creation.')
  if(request.mode!=='validate-only'&&(archive.purpose!=='campaign-backup'||actor.role!=='gm'||request.actorAuthorityDefinitionSha256!==actor.definitionSha256))fail('breeding.archive.unauthorized','request.mode','restore requires an authenticated GM and a campaign-backup archive.')
  if(request.mode==='replace-campaign'&&request.expectedCurrentArchiveDefinitionSha256!==input.currentArchiveDefinitionSha256)fail('breeding.archive.cross-link','request.expectedCurrentArchiveDefinitionSha256','does not match the current backup checkpoint.')
  if(request.mode==='restore-new-campaign'&&input.currentArchiveDefinitionSha256!==null)fail('breeding.archive.cross-link','request.mode','new-campaign restore requires an empty target.')
  for(const chunk of archive.chunks)for(const record of chunk.records)if(!input.validateRecordDependencies(chunk.recordKind,record))fail('breeding.archive.cross-link',`archive.${chunk.recordKind}`,'contains a canonical identity unavailable from the bound app-owned references.')
  if(archive.rulesetId!==references.rulesetId||archive.rulesetDefinitionSha256!==references.rulesetDefinitionSha256||archive.referenceVersions.definitionSha256!==references.definitionSha256)fail('breeding.archive.cross-link','archive.referenceVersions','must match every current ruleset and reference version exactly.')
  if(archive.purpose==='campaign-backup')validateBackupLinks(archive)
  return Object.freeze({archive,request,recordCounts:archiveCounts(archive)})
}
export const validateLegacyLineageReviewAttachmentV1=(input:{readonly review:unknown,readonly pokemonSheet:{readonly slug:string,readonly revision:number,readonly definitionSha256:string},readonly origin:unknown|null}):{readonly decision:'compatibility-only'|'reject',readonly origin:null}|{readonly decision:'attach-existing-origin',readonly origin:PokemonBreedingOriginV1}=>{
  const review=parseAuthoritativeBreedingLegacyLineageReviewV1(input.review)
  if(review.pokemonSheetSlug!==input.pokemonSheet.slug||review.pokemonSheetRevision!==input.pokemonSheet.revision||review.pokemonSheetDefinitionSha256!==input.pokemonSheet.definitionSha256)fail('breeding.archive.cross-link','legacyReview.pokemonSheetSlug','must bind the exact current Pokémon sheet revision.')
  if(review.decision!=='attach-existing-origin'){if(input.origin!==null)fail('breeding.archive.cross-link','origin','cannot attach lineage for a compatibility-only or rejected review.');return Object.freeze({decision:review.decision,origin:null})}
  const origin=parseAuthoritativePokemonBreedingOriginV1(input.origin)
  if(review.existingOriginId!==origin.originId||review.existingOriginDefinitionSha256!==origin.lineageDefinitionSha256||origin.childSheetSlug!==review.pokemonSheetSlug)fail('breeding.archive.cross-link','legacyReview.existingOriginId','must attach only an already-authoritative origin for this child; legacy Move fields never manufacture lineage.')
  return Object.freeze({decision:'attach-existing-origin',origin})
}
export const assertBreedingArchiveExactReplayV1=(existingValue:unknown,replayedValue:unknown):BreedingArchiveV1=>{const existing=parseAuthoritativeBreedingArchiveV1(existingValue,'existingArchive');const replayed=parseAuthoritativeBreedingArchiveV1(replayedValue,'replayedArchive');if(existing.archiveId!==replayed.archiveId||!equalStrict(existing,replayed))fail('breeding.archive.identity-collision','replayedArchive.archiveId','allows only byte-semantic exact stable-JSON replay.');return existing}
export const assertBreedingArchiveImportRequestExactReplayV1=(existingValue:unknown,replayedValue:unknown):BreedingArchiveImportRequestV1=>{const existing=parseAuthoritativeBreedingArchiveImportRequestV1(existingValue,'existingImportRequest');const replayed=parseAuthoritativeBreedingArchiveImportRequestV1(replayedValue,'replayedImportRequest');if(existing.requestId!==replayed.requestId||!equalStrict(existing,replayed))fail('breeding.archive.identity-collision','replayedImportRequest.requestId','allows only exact stable-JSON replay.');return existing}
export const assertBreedingArchiveRestoreReceiptExactReplayV1=(existingValue:unknown,replayedValue:unknown):BreedingArchiveRestoreReceiptV1=>{const existing=parseAuthoritativeBreedingArchiveRestoreReceiptV1(existingValue,'existingRestoreReceipt');const replayed=parseAuthoritativeBreedingArchiveRestoreReceiptV1(replayedValue,'replayedRestoreReceipt');if(existing.requestId!==replayed.requestId||!equalStrict(existing,replayed))fail('breeding.archive.identity-collision','replayedRestoreReceipt.requestId','allows only exact stable-JSON replay.');return existing}
export const assertBreedingMigrationExactReplayV1=(existingValue:unknown,replayedValue:unknown):BreedingMigrationPackageV1=>{const existing=parseAuthoritativeBreedingMigrationPackageV1(existingValue,'existingMigration');const replayed=parseAuthoritativeBreedingMigrationPackageV1(replayedValue,'replayedMigration');if(existing.migrationId!==replayed.migrationId||!equalStrict(existing,replayed))fail('breeding.archive.identity-collision','replayedMigration.migrationId','allows only exact stable-JSON replay.');return existing}
export const assertBreedingLegacyReviewExactReplayV1=(existingValue:unknown,replayedValue:unknown):BreedingLegacyLineageReviewV1=>{const existing=parseAuthoritativeBreedingLegacyLineageReviewV1(existingValue,'existingLegacyReview');const replayed=parseAuthoritativeBreedingLegacyLineageReviewV1(replayedValue,'replayedLegacyReview');if(existing.reviewId!==replayed.reviewId||!equalStrict(existing,replayed))fail('breeding.archive.identity-collision','replayedLegacyReview.reviewId','allows only exact stable-JSON replay.');return existing}
export const archiveRecordCounts=archiveCounts
