export const BREEDING_DOCUMENTATION_CLOSURE_V1 = Object.freeze({
  schemaVersion: 1 as const,
  closureId: 'ptu-1.05-breeding-documentation-closure-v1' as const,
  ticket: 'BR-088' as const,
  categories: Object.freeze([
    Object.freeze({
      categoryId: 'contributor' as const,
      path: 'docs/breeding/contributor-guide.md' as const,
      requiredHeadings: Object.freeze([
        '## Documentation map',
        '## Source rules',
        '## Commands and use cases',
        '## Archive and migration changes',
        '## Performance budget changes',
        '## Production-like acceptance changes',
        '## Tests',
        '## Completion checklist',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'operator' as const,
      path: 'docs/breeding/operator-guide.md' as const,
      requiredHeadings: Object.freeze([
        '## Current rollout state',
        '## Workshop shell triage',
        '## Campaign-clock Egg batches',
        '## BR-085 archive and migration release checks',
        '## BR-086 performance release checks',
        '## BR-087 production-like acceptance',
        '## Recovery principles',
        '## Backup and restore',
        '## Rollback',
        '## Escalation evidence',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'gm' as const,
      path: 'docs/breeding/gm-and-player-guide.md' as const,
      requiredHeadings: Object.freeze([
        '## GM workflow',
        '### Advance campaign time',
        '### Resolve checks and reviewed choices',
        '### Hatch special review',
        '### Consent limits',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'player' as const,
      path: 'docs/breeding/gm-and-player-guide.md' as const,
      requiredHeadings: Object.freeze([
        '## Player workflow',
        '### Create a Project',
        '### Grant or revoke Project consent',
        '### Offer or accept an Egg gift',
        '### Hatch an Egg',
        '## Shared-table privacy',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'api' as const,
      path: 'docs/breeding/api-reference.md' as const,
      requiredHeadings: Object.freeze([
        '## Common protocol',
        '## Endpoint summary',
        '## `GET /api/breeding/workshop`',
        '## `GET /api/breeding/workshop/activity`',
        '## `POST /api/breeding/projects/wizard`',
        '## `POST /api/breeding/projects/wizard/guidance`',
        '## `POST /api/breeding/projects/wizard/choices`',
        '## `POST /api/breeding/hatch`',
        '## `POST /api/breeding/consent`',
        '## Non-HTTP operational surfaces',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'data-model' as const,
      path: 'docs/breeding/data-model-and-campaign-clock.md' as const,
      requiredHeadings: Object.freeze([
        '## Authority model',
        '## Project aggregate',
        '## Egg aggregate',
        '## Operation and evidence model',
        '## SQLite persistence map',
        '## Transaction groups',
        '## Archive and migration model',
        '## Invariants for schema changes',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'campaign-clock' as const,
      path: 'docs/breeding/data-model-and-campaign-clock.md' as const,
      requiredHeadings: Object.freeze([
        '## Campaign-clock semantics',
        '### Singleton authority',
        '### Project timeline',
        '### Egg incubation',
        '### Long skips and bounded continuation',
        '### Expiry and cooldown',
      ] as const),
    }),
    Object.freeze({
      categoryId: 'qa' as const,
      path: 'docs/breeding/qa-and-release-guide.md' as const,
      requiredHeadings: Object.freeze([
        '## Test layers',
        '### 4. Performance release gates',
        '### 5. Production-like acceptance',
        '### 6. Archive and migration acceptance',
        '### 8. Integrated closure',
        '## Manual GM/player matrix',
        '## Campaign-clock QA matrix',
        '## Consent and privacy QA',
        '## Hatch atomicity QA',
        '## Accessibility and responsive QA',
        '## Documentation QA',
        '## Sign-off rule',
      ] as const),
    }),
  ]),
  runtimeBindings: Object.freeze({
    workshopApiCount: 7 as const,
    projectStatusCount: 12 as const,
    eggStatusCount: 7 as const,
    eggSourceKindCount: 4 as const,
    commandKindCount: 22 as const,
    baseAudienceCount: 5 as const,
    storageSchemaVersion: 28 as const,
    postBodyMaximumUtf8Bytes: 32 * 1024,
    archiveMaximumUtf8Bytes: 64 * 1024 * 1024,
    campaignClockEggBatchMaximum: 100 as const,
    initialProjectMinutes: 240 as const,
    breederCheckDifficultyClass: 12 as const,
    additionalProjectMinutes: 240 as const,
    minimumProjectMinutesBeforeEgg: 480 as const,
  }),
  requiredCrossLinks: Object.freeze([
    'docs/breeding/accessibility-responsive-and-table-distance.md',
    'docs/breeding/api-reference.md',
    'docs/breeding/architecture-and-ownership.md',
    'docs/breeding/contributor-guide.md',
    'docs/breeding/data-model-and-campaign-clock.md',
    'docs/breeding/gm-and-player-guide.md',
    'docs/breeding/operator-guide.md',
    'docs/breeding/qa-and-release-guide.md',
    'docs/breeding/security-and-privacy.md',
    'docs/breeding/workshop.md',
  ] as const),
  prohibitedAuthorityClaims: Object.freeze([
    'browser-time-is-campaign-time',
    'gm-may-substitute-positive-consent',
    'egg-is-a-pokemon-sheet-before-hatch',
    'map-or-inventory-is-egg-authority',
    'client-may-submit-resolved-mechanics',
    'css-is-the-privacy-boundary',
    'diagnostics-authorize-orphan-repair',
    'terminal-retry-reruns-mechanics',
  ] as const),
  verificationCommand: 'npm run check:breeding-documentation' as const,
})

export const BREEDING_DOCUMENTATION_CLOSURE_DEFINITION_SHA256 =
  'b7c0dc3a22e73767107971694f4fb6d152e834ea5e7d57174a09fe67bea57f01' as const
