import type { MoveSpec,MoveSpecCostDeclaration,MoveSpecTargetingDeclaration } from '#shared/moveAutomation/spec'
import type { MoveSpecV2Registration } from '../registry'
import { REACTION_STAGE_258_265_HANDLER_ID } from '../handlers/reactionStage258_265'
import { areaTargeting,automaticSetupExecuteCost,createReviewedMoveSpec,selfTargeting,singleTargeting,standardActionCost } from './reviewedSpecBuilder'
export const MA_258_265_MOVE_NAMES=Object.freeze(['Ally Switch','Assurance','Baneful Bunker','Beak Blast','Beat Up','Bide','Burning Jealousy','Counter','Crafty Shield','Detect','Disable','Endure','Expanding Force','Feint','Flower Shield','Focus Punch','Follow Me','Grudge','High Jump Kick','Instruct','Jump Kick','Kinesis','King’s Shield','Magic Coat','Mat Block','Me First','Memento','Metronome','Mirror Coat','Obstruct','Phantom Force','Powder','Protect','Psychic Terrain','Pursuit','Quick Guard','Rage Powder','Rising Voltage','Shadow Force','Shell Trap','Sky Uppercut','Snatch','Spiky Shield','Spite','Sucker Punch','Teleport','Vital Throw','Wide Guard','After You','Agility','Amnesia','Ancient Power','Attract','Aura Wheel','Brick Break','Bug Bite','Bulk Up','Calm Mind','Chip Away','Clanging Scales','Coil','Constrict','Cosmic Power','Cotton Guard'] as const)
export type ReactionStageCohort258265MoveName=(typeof MA_258_265_MOVE_NAMES)[number]
const SELF=new Set(['Baneful Bunker','Beak Blast','Bide','Detect','Endure','Feint','Focus Punch','Follow Me','Grudge','Kinesis','King’s Shield','Magic Coat','Mat Block','Me First','Memento','Metronome','Mirror Coat','Obstruct','Phantom Force','Protect','Quick Guard','Rage Powder','Shadow Force','Shell Trap','Snatch','Spiky Shield','Spite','Sucker Punch','Teleport','Wide Guard','Agility','Amnesia','Bulk Up','Calm Mind','Coil','Cosmic Power','Cotton Guard'])
const AREA=new Set(['Beat Up','Bide','Burning Jealousy','Crafty Shield','Expanding Force','Flower Shield','Mat Block','Psychic Terrain','Quick Guard','Rage Powder','Rising Voltage','Wide Guard'])
const FIELD=new Set(['Psychic Terrain'])
const REACT=new Set(['Ally Switch','Baneful Bunker','Bide','Counter','Crafty Shield','Detect','Disable','Endure','Feint','Grudge','Kinesis','King’s Shield','Magic Coat','Mat Block','Me First','Mirror Coat','Obstruct','Protect','Pursuit','Quick Guard','Shell Trap','Sky Uppercut','Snatch','Spiky Shield','Spite','Sucker Punch','Teleport','Vital Throw','Wide Guard'])
const SETUP=new Set(['Beak Blast','Focus Punch','Phantom Force','Shadow Force'])
const targeting=(n:string):MoveSpecTargetingDeclaration=>FIELD.has(n)?{kind:'field',minTargets:0,maxTargets:0,selector:null}:AREA.has(n)?areaTargeting({relationship:'any',willingness:'any',excludeActor:false}):SELF.has(n)?selfTargeting():singleTargeting()
const sl=(n:string)=>n.normalize('NFKD').replace(/[’']/g,'').replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()
const costs=(n:string):readonly MoveSpecCostDeclaration[]=>{if(REACT.has(n))return[{id:`${sl(n)}.cost.interrupt`,phase:'declare',cost:{kind:'action-resource',resource:'interrupt',amount:1}}];const c=[standardActionCost(sl(n))];if(SETUP.has(n))c.push(automaticSetupExecuteCost(sl(n)));return c}
const specs=Object.fromEntries(MA_258_265_MOVE_NAMES.map(canonicalId=>[canonicalId,createReviewedMoveSpec({canonicalId,targeting:targeting(canonicalId),costs:costs(canonicalId),operations:[],registeredHandlerId:REACTION_STAGE_258_265_HANDLER_ID,tags:['reaction-stage-context','reviewed']})])) as Record<ReactionStageCohort258265MoveName,MoveSpec>
export const REACTION_STAGE_COHORTS_258_265_MOVE_SPEC_REGISTRATIONS:readonly MoveSpecV2Registration[]=Object.freeze(MA_258_265_MOVE_NAMES.map(canonicalId=>Object.freeze({canonicalId,sourceModule:'server/domain/moveAutomation/specs/reactionStageCohorts258_265.ts',spec:specs[canonicalId]})))
